### ISSUE TITLE
https not working with self signed certificates

### ISSUE THREAD

**Issue by tkwatson63** [home-assistant/homebridge-homeassistant#10]
Everything works just fine with http after setting up SSL on HA with a self signed cert and changing config.json to point to https instead of http I cannot get HB to start. Can capture output if necessary.

**Comment by subutux** [comment]
Try this before you execute homebridge:
```bash
export NODE_TLS_REJECT_UNAUTHORIZED=0
```

**Comment by maddox** [comment]
Yeah, it sounds like it's rejecting your self signed cert. Are you using a self signed cert, or a Let's Encrypt cert. If the former, you should consider migrating to the later.

**Comment by robbiet480** [comment]
:+1: for @maddox. Closing as this isn't a homebridge-homeassistant issue.

**Comment by robbiet480** [comment]
Added a note about this use case to the README [here](https://github.com/home-assistant/homebridge-homeassistant#using-with-self-signed-ssl-certificates).

**Comment by maddox** [comment]
👏

**Comment by kolossboss** [comment]
Hi,

I'm running into the same problem.

I have an trusted certificate valid for my DNS address but not my local HA address. HA has no issues and works great with this certificate.

What do you exactly mean with 

> Try this before you execute homebridge:
> 
> `export NODE_TLS_REJECT_UNAUTHORIZED=0`

How can I do this `export NODE_TLS_REJECT_UNAUTHORIZED=0` when I autostart Homebridge with systemd.server?

I dont get it to work

**Comment by kolossboss** [comment]
OK found a nice and easy solution.

I simply modified the homebridge executable set up file .

This file is located here:

`/usr/lib/node_modules/homebridge/bin`

Just added the command: `process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";`

Then the file look like this:

```
#!/usr/bin/env node

//
// This executable sets up the environment and runs the HomeBridge CLI.
//

'use strict';

process.title = 'homebridge';

// Find the HomeBridge lib
var path = require('path');
var fs = require('fs');
var lib = path.join(path.dirname(fs.realpathSync(__filename)), '../lib');
process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";

// Run HomeBridge
require(lib + '/cli')();
```

Now restart homebridge service. And the ssl errors are gone.

NOTE: THIS DISABLES ALL KINDS OF SECURITY CHECKS

I dont know if this is the right way but this works for me and works this autostart and systemd service
