### ISSUE TITLE
co2 not showing

### ISSUE THREAD

**Issue by sirdir1972** [home-assistant/homebridge-homeassistant#101]
netatmo co2 sensors are not showing via homeassistant-homebridge, not even when I set homebridge_sensor_type to co2

**Comment by robbiet480** [comment]
Can you share your entity JSON? Just change your URL add `/api/states` on the end, i.e. `http://localhost:8123/api/states/<entity_id>?api_password=<myapipassword>` where `<entity_id>` is the sensor you expect to show.

**Comment by sirdir1972** [comment]
Hi!

Sure:

{"attributes": {"friendly_name": "Wohnzimmer CO2", "homebridge_sensor_type": "co2", "icon": "mdi:cloud", "unit_of_measurement": "ppm"}, "entity_id": "sensor.netatmo_wohnzimmer_co2", "last_changed": "2017-02-02T22:59:55.028263+00:00", "last_updated": "2017-02-02T22:59:55.028263+00:00", "state": "621"}

**Comment by robbiet480** [comment]
How did you install `homebridge-homeassistant` to test this?

**Comment by sirdir1972** [comment]
Hi!

What do you mean? the plugin?

The relevant part is
        {
            "platform": "HomeAssistant",
            "name": "HomeAssistant",
            "host": "https://192.168.1.19:8123",
            "password": „*censored*",
            "supported_types": ["binary_sensor", "cover", "fan", "input_boolean", "light", "lock", "media_player", "scene", "sensor", "switch"]
        }

other values like Temperature (max, min), humidity do get through, but co2 (and air quality) don’t.

**Comment by robbiet480** [comment]
What `npm` command did you use? The co2 support has not yet been published so you should've installed via `npm install -g home-assistant/homebridge-homeassistant`

**Comment by robbiet480** [comment]
@sirdir1972 npm just got updated, you should now be able to normally upgrade (`npm install -g homebridge-homeassistant`).

**Comment by sirdir1972** [comment]
Hi!

I wasn’t aware co2 is only supported in a ‚special‘ version. I had only the ‚normal‘ version installed, indeed.

Regards
patrick

**Comment by sirdir1972** [comment]
Hi!

Don’t know whether it’s a coincidence or not: When I installed the ‚normal‘ version (which seems to be 2.0.2) I still couldn’t see co2, even after waiting some minutes. 
Then I installed the ‚unpublished‘ verseion, which was listed as 2.0.1 and co2 showed up at once. 
Then I reinstalled the published 2.0.2 and co2 seems to be still there… fine.

Now the most annoying thing is that many components keep moving to ‚standardroom‘, but that’s another story. 

Thank you.

**Comment by robbiet480** [comment]
Maybe you had installed in a weird place previously and Homebridge was using that older version? CO2 is now in the normal version, I only release a new normal version every few weeks, so if you want the special new features you have to install it via a special method :)

Glad you got this figured out!

**Comment by sirdir1972** [comment]
I don’t think so, I don’t even know how to change the path ;) … and I installed both versions just like you wrote. but anyway, it works now ;)
