### ISSUE TITLE
Expose Groups to HomeBridge

### ISSUE THREAD

**Issue by CCOSTAN** [home-assistant/homebridge-homeassistant#102]
Is it possible to expose groups to Homebridge like I do with Emulated_hue?  This way I can have one consistent group area in HASS and all voice commands will react alike.

**Comment by robbiet480** [comment]
Expose as switches I assume?

**Comment by CCOSTAN** [comment]
Yeah .. So I can just say 'Siri, turn off the kitchen lights' without having to assign the lights to rooms or anything.  This is the way I use Emulated_hue so I don't have to manage groups in my Alexa app.  If groups are exposed, we can just drop everything in the default room and be done with the Home App on IOS.
