### ISSUE TITLE
Undefined error since upgrading HomeAssistant to 0.38

### ISSUE THREAD

**Issue by jsg4** [home-assistant/homebridge-homeassistant#114]
Seeing this in log now, Homebridge won't work.

Feb 15 07:50:30 jonathan-HA homebridge[15017]: undefined:1

Feb 15 07:50:41 jonathan-HA homebridge[15042]: [2/15/2017, 7:50:41 AM] [HomeAssistant] Initializing platform accessory 'Wine Cellar'...
Feb 15 07:50:41 jonathan-HA homebridge[15042]: [2/15/2017, 7:50:41 AM] [HomeAssistant] Initializing platform accessory 'Mudroom Lights'...
Feb 15 07:50:41 jonathan-HA homebridge[15042]: [2/15/2017, 7:50:41 AM] [HomeAssistant] Initializing platform accessory 'Second Floor Hallway'...
Feb 15 07:50:41 jonathan-HA homebridge[15042]: [2/15/2017, 7:50:41 AM] [HomeAssistant] Initializing platform accessory 'Family Room Motion'...
Feb 15 07:50:41 jonathan-HA homebridge[15042]: [2/15/2017, 7:50:41 AM] [HomeAssistant] Initializing platform accessory 'Family Room Movie Paused'...
Feb 15 07:50:41 jonathan-HA homebridge[15042]: [2/15/2017, 7:50:41 AM] [HomeAssistant] Initializing platform accessory 'Kitchen Main'...
Feb 15 07:50:41 jonathan-HA homebridge[15042]: [2/15/2017, 7:50:41 AM] [HomeAssistant] Initializing platform accessory 'Third Floor Stairs'...
Feb 15 07:50:41 jonathan-HA homebridge[15042]: [2/15/2017, 7:50:41 AM] [HomeAssistant] Initializing platform accessory 'Away'...
Feb 15 07:50:41 jonathan-HA homebridge[15042]: [2/15/2017, 7:50:41 AM] [HomeAssistant] Initializing platform accessory 'Nightstand Right'...
Feb 15 07:50:41 jonathan-HA homebridge[15042]: [2/15/2017, 7:50:41 AM] [HomeAssistant] Initializing platform accessory 'Good Night'...
Feb 15 07:50:41 jonathan-HA homebridge[15042]: [2/15/2017, 7:50:41 AM] [HomeAssistant] Initializing platform accessory 'Home Thermostat (Third Floor) target'...
Feb 15 07:50:41 jonathan-HA homebridge[15042]: [2/15/2017, 7:50:41 AM] [HomeAssistant] Initializing platform accessory 'Basement Right'...
Feb 15 07:50:41 jonathan-HA homebridge[15042]: [2/15/2017, 7:50:41 AM] [HomeAssistant] Initializing platform accessory 'Home Thermostat (Master Bedroom) target'...
Feb 15 07:50:41 jonathan-HA homebridge[15042]: [2/15/2017, 7:50:41 AM] [HomeAssistant] Initializing platform accessory 'Bedroom Movie'...
Feb 15 07:50:41 jonathan-HA homebridge[15042]: [2/15/2017, 7:50:41 AM] [HomeAssistant] Initializing platform accessory 'Home Thermostat (Master Bedroom) temperature'...
Feb 15 07:50:41 jonathan-HA homebridge[15042]: [2/15/2017, 7:50:41 AM] [HomeAssistant] Initializing platform accessory 'Office Lights'...
Feb 15 07:50:42 jonathan-HA homebridge[15042]: undefined:1
Feb 15 07:50:42 jonathan-HA systemd[1]: homebridge.service: Main process exited, code=exited, status=1/FAILURE
Feb 15 07:50:42 jonathan-HA systemd[1]: homebridge.service: Unit entered failed state.
Feb 15 07:50:42 jonathan-HA systemd[1]: homebridge.service: Failed with result 'exit-code'.
Feb 15 07:50:52 jonathan-HA systemd[1]: homebridge.service: Service hold-off time over, scheduling restart.

**Comment by johanlkarlsson** [comment]
It works for me, but no media_player devices are imported.

**Comment by robbiet480** [comment]
Fixed in #112, will be on npm tomorrow. In the mean time run `npm install -g home-assistant/homebridge-homeassistant` to install the latest code from GitHub.

**Comment by jsg4** [comment]
Same issue 

Feb 19 07:53:08 jonathan-HA homebridge[27656]: [2/19/2017, 7:53:08 AM] [HomeAssistant] Initializing platform accessory 'Foyer Lights'...
Feb 19 07:53:08 jonathan-HA homebridge[27656]: undefined:1
Feb 19 07:53:08 jonathan-HA systemd[1]: homebridge.service: Main process exited, code=exited, status=1/FAILURE
Feb 19 07:53:08 jonathan-HA systemd[1]: homebridge.service: Unit entered failed state.
Feb 19 07:53:08 jonathan-HA systemd[1]: homebridge.service: Failed with result 'exit-code'.
