### ISSUE TITLE
Option to disable brightness setting on lights

### ISSUE THREAD

**Issue by Phontana** [home-assistant/homebridge-homeassistant#120]
I have some lights in my configuration that support settings brightness, but most of them don't. However, it is possible in HomeKit to set the brightness which doesn't make sense. Is it possible to add a customize flag (of something else) to prevent some lights from showing brightness controls?

**Comment by robbiet480** [comment]
@tobre6

**Comment by tobre6** [comment]
Yay :)

**Comment by tobre6** [comment]
@Phontina I think this PR resolves the issue https://github.com/home-assistant/homebridge-homeassistant/pull/121
Can you confirm?

**Comment by Phontana** [comment]
Yes, I think it will resolve the issue perfectly. Thanks!

**Comment by robbiet480** [comment]
Closing as such, will release that fix to npm momentarily.

**Comment by Phontana** [comment]
I updated through npm, but it doesn't fix the issue for me. I restarted homebridge to apply changes. Is it possible that Homebridge advertises all the lights with the brightness feature enabled? My lights are configured through the `rfxtrx` component.

**Comment by tobre6** [comment]
What does the entity attributes say?

**Comment by Phontana** [comment]
It says `supported_features: 1`. I didn't know I could see the `supported_features` tag, but it makes sense to me now. I think my issue is in the `rfxtrx` component. Thanks for your help.
