### ISSUE TITLE
All accessories stuck on "Updating" in HomeKit. 

### ISSUE THREAD

**Issue by mixographer** [home-assistant/homebridge-homeassistant#123]
I updated my Homebridge, and my homebridge-homeassistant, and now all my accessories are stuck in "Updating" in the Homekit app. If I forcetouch the icon, it says "The device is not responding."

All my accessories work fine in homeassistant, but not over the bridge. Also, Hue lights work fine in the HomeKit app. It is only items on the Homebridge that don't work.

**Comment by robbiet480** [comment]
Any errors in your logs? Can you enable extra logging in your configuration to ensure you are seeing data coming through correctly?

**Comment by mixographer** [comment]
I think another npm I loaded, homebridge-neopixel was blocking if the accessory didn't respond. I don't think this is an issue in homebridge-homeassistant. I think this issue can safely be closed. If I do find an issue in homebridge-homeassistant I'll open a new issue. Thanks.
