### ISSUE TITLE
Could not find binary_sensor

### ISSUE THREAD

**Issue by Guoer-xz** [home-assistant/homebridge-homeassistant#126]
I use this command ：npm install -g homebridge-homeassistant
Installation of other parts of the plug-in is normal, except binary_sensor
  A few days ago binary_sensor can also view the use in home, suddenly there is no recovery, even if the system cannot be re enabled, and the other part of the work of the plug-in is very good, how should I go to the investigation, thank you
Here is my config：

{
                    "platform": "HomeAssistant",
                    "name": "HomeAssistant",
                    "host": "http://192.168.xx.xx:xxxx",
                    "password": "xxxxx",
                    "supported_types": ["binary_sensor", "cover", "fan", "input_boolean", "light", "lock", "media_player", "scene", "sensor", "switch"]
                    }

**Comment by robbiet480** [comment]
Closed via #125.
