### ISSUE TITLE
Devices (switches, binary sensors) not showing up

### ISSUE THREAD

**Issue by pcragone** [home-assistant/homebridge-homeassistant#130]
Please point me in the right direction if there's a better place to get some help on this.

I've got a couple binary sensors and a switch that work fine in HASS (and they're labeled as binary_sensor. and switch. appropriately), but don't show up in HomeKit.  I'm not seeing any errors in the logs, but maybe I'm missing something.  The devices are not hidden from HomeKit through customization.  I can't seem to think of any reason they're not showing up.  Any thoughts on this?

**Comment by cwixon** [comment]
Is this a new problem with an updated copy of Home Assistant?  They recently (0.39?) changed sensor_class to device_class (which is mandatory for binary sensors in homebridge-homeassistant -- see the README) but there isn't a release of this plugin that handles the change, as far as I know.  The version in git does.

Don't know about the switches though.  I have switches that show up fine.

**Comment by robbiet480** [comment]
Will push a new version to npm now

**Comment by robbiet480** [comment]
2.0.7 published
