### ISSUE TITLE
Lost all devices on power loss

### ISSUE THREAD

**Issue by pcragone** [home-assistant/homebridge-homeassistant#132]
It seems my house lost power yesterday.  In that episodes, it seems homebridge, homebridge-assistant, and/or homekit had a bit of a fit, and no devices show up on homekit.  Additionally, I've manually removed the associations in homekit, and now nothing will show up at all.  Homebridge and homeassistant all seem to be running fine - I can control everything through homeassistant.  It's just nothing is showing up in Homekit.

For what it's worth, I've been trying to use my Apple TV 3rd gen as a hub for homekit - the Home app on my iPhone recognizes that the Apple TV wants to be the hub, but there's no option for Home/Homekit on the Apple TV -> Settings -> iCloud page.  (I called Apple support about that, they couldn't help.)

**Comment by robbiet480** [comment]
I'm assuming what happened is your state file got corrupted. Try removing everything except `config.json` from the `~/.homebridge` directory.
