### ISSUE TITLE
Customization of lights as fans within HomeKit

### ISSUE THREAD

**Issue by schmittx** [home-assistant/homebridge-homeassistant#139]
In HASS, many Z-wave fan controllers show up as generic dimmers (lights).

Until there's a solution within HASS to convert these to fans (via a fan template component, Z-wave fan component, etc.), is it possible to make these appear as fans within HomeKit? This version ([link](https://www.npmjs.com/package/homebridge-wink2)) of the homebridge-wink plugin has a similar feature.

From a bigger picture, could a "homebridge_type" attribute be added within customize to control whether an entity shows up as light, switch, fan, outlet (see other feature request), etc.?

I'd love to help but I have minimal programming experience and am trying to learn at the moment. For now, I can only offer ideas.

**Comment by robbiet480** [comment]
I don't think this is possible as a light has totally different properties from a fan so I wouldn't want to coerce it...

**Comment by schmittx** [comment]
It's definitely possible as I just confirmed using a Cree light bulb (Zigbee) and Leviton DZMX1 dimmer (Z-wave), I was able to follow instructions for the Homebridge-Wink2 plugin to "convert" these to fans within HomeKit.

(note, I updated link in original post)

**Comment by schmittx** [comment]
Disregard due to addition of Z-wave fan support within Home Assistant.
