### ISSUE TITLE
Problem with device name

### ISSUE THREAD

**Issue by yeralin** [home-assistant/homebridge-homeassistant#141]
Hi,

I'm using switch "[Wake on LAN Switch](https://home-assistant.io/components/switch.wake_on_lan/)". I gave it name `Computer`.
Everything works fine like when I say "Siri, turn on Computer" or "Siri, turn off Computer".

But sometimes, Siri replies with something like "I don't know what Computer is", but if I manually go to "Home" app, I can see switch available, and I can use it (switch it manually).
Do you know what can cause this?

**Comment by maddox** [comment]
Siri is dumb. I know this is a trite and hostile answer, but it's the truth.

Siri does the same sort of random things when asking to text a name on your contact list. Lots of times it will pick the right "john" and other times it will ask you "which john?"

There's no rhyme or reason and it's one of the fundamental reasons people get frustrated with Siri. It's not very consistent with its results.
