### ISSUE TITLE
Device limit

### ISSUE THREAD

**Issue by kentcalero** [home-assistant/homebridge-homeassistant#142]
Is there a device limit, homebridge-homeassistant stopped working when I added my ISY To home assistant. The ISY brought along about 80 or so devices, in addition to the 20 or so in hass.

**Comment by robbiet480** [comment]
[The maximum number of accessories allowed by iOS is 100.](https://github.com/nfarina/homebridge/issues/827#issuecomment-251146385)

**Comment by CCOSTAN** [comment]
@robbiet480 Is it possible to list the device count somewhere?  Either in the initial log or somehow expose it in HA as a Sensor?  I'm past the 100 limit and need to pare it all back but want to ride the line perfectly at 99. :) 

THANKS
Carlo

**Comment by kevinfoerster** [comment]
@CCOSTAN I have had the same question, after digging around, I found the home.app exposes the number of devices/accessories, it is shown when you select the Bridge itself under "devices" (in my case Geräte)

![img_2cfa4e7e1bed-1](https://user-images.githubusercontent.com/163305/44961436-84ac7680-af11-11e8-8fd6-dba8b0edfab7.jpeg)
