### ISSUE TITLE
No effect on customization for homebridge

### ISSUE THREAD

**Issue by Nicxe** [home-assistant/homebridge-homeassistant#145]
I have just installed homebridge on my rPi and have successful connected home assistant. But now I want to hide some switches, sensors and lamps in the "Home" app on the iPhone. So I am customizing Home Assistant customization configuration with this entry but the switch will not disappear.

```
customize:
  switch.a_switch:
    homebridge_hidden: true
```

How do I get home bridge to react to the changes I have made in home assistant config file?

**Comment by Nicxe** [comment]
Started to work after a couple of days

**Comment by okand** [comment]
In case someone else ends up here through a search engine.

`customize:` needs to be placed under the `homeassistant:` block at the top of the file. Indented one step like `name:`, `latitute:`, `longitude:`, and such are.
