### ISSUE TITLE
Problem with maxcube thermostate

### ISSUE THREAD

**Issue by tobsch** [home-assistant/homebridge-homeassistant#148]
Hi there,

unfortunately, the maxcube thermostate in a lot of cases responds with the string "unknown" in the current temperature.
This leads to a totally not working homebridge.

Any ideas?

Tobias

**Comment by robbiet480** [comment]
This is hard for me to debug as I don't have any climate devices. Maybe ask the original author for assistance?

**Comment by robbiet480** [comment]
Can you test again with the new version I am about to publish? It will include the improvements from #178.
