### ISSUE TITLE
exclude devices

### ISSUE THREAD

**Issue by snizzleorg** [home-assistant/homebridge-homeassistant#15]
Ayn way to ignore devices? I have a lot of devices and some can be directly managed via homekit.

**Comment by airdamien** [comment]
I'm looking for the same ability. Lights means everything Hue basically gets duplicated, but my GE Z-wave in-wall dimmer is only avail through homeassistant (usb device ownership). 
Instead of an exclude, maybe a specific include by entity_id?

**Comment by airdamien** [comment]
https://github.com/home-assistant/homebridge-homeassistant/blob/master/index.js

I think that I can wire it in manually with something like this.. pseudocode at best, haven't gone home to try it yet. 

var allowedLight = new Boolean();

switch (entity) {
  case "light.ge_switch_2":
  case "light.ge_dimmer_3blah":
          allowedLight = true;
          break;
  default:
    console.log("Light is NOT in the allowed list");
}

   if (entity_type == 'light' && allowedLight) {
          accessory = new HomeAssistantLight(that.log, entity, that)
        }else if (entity_type == 'switch'){

**Comment by airdamien** [comment]
this is working for me. 

        console.log(entity.entity_id);
        if (entity_type == 'light' && entity.entity_id == 'light.ge_12724_3way_dimmer_switch_level_4' ) {
          console.log(entity.entity_id);
          console.log("Light is allowed, configuring");
          accessory = new HomeAssistantLight(that.log, entity, that)

**Comment by KmanOz** [comment]
+1 on this. I have a bunch of mqtt switches in HA that are dummies primarily used for logic that I really don't want in Homebridge. In fact sometimes when I muddle my words and Homebridge misinterprets my command HA goes haywire as it tries to turn on/off switches that shouldn't be touched. What would be neat is a way of flagging assets in HA that are automatically sucked in by the plugin rather than sucking in everything. I wish I knew .js I would give that code a go.

**Comment by abouzek** [comment]
Can't you pair the HomeBridge with HomeKit and then manually remove devices you don't want in a third-party app like Home?

**Comment by KmanOz** [comment]
Well using Apple's Home app, I can't see where you can remove individual accessories. You can preclude them from showing up as a status on the main page of home or you can not add them to favorites but that's about it, they still appear. I created a room for all the stuff I don't need and put all the switches I don't need in there but being able to control what goes in would be a better solution.

**Comment by snizzleorg** [comment]
is this on npm already?

**Comment by robbiet480** [comment]
Not yet, you can get the latest by running npm install -g
home-assistant/homebridge-homeassistant.

-- 
Robbie Trencheny (@robbie <http://twitter.com/robbie>)
925-884-3728
robbie.io

**Comment by robbiet480** [comment]
Not yet, you can get the latest by running `npm install -g home-assistant/homebridge-homeassistant`.

**Comment by nashlib** [comment]
Cannot get Homebridge to exclude items from home-assistant. I did add the customise in confuguration.yaml file of HA.

**Comment by maddox** [comment]
Can you confirm the version of the plugin you're using and paste in your customize config for your devices that you are trying to ignore?

**Comment by nashlib** [comment]
im using HA 0.30.2 and my config file is like this.

`homeassistant:
  customize:
    switch.aeotec_zw096_smart_switch_6_switch_2:
      friendly_name: Second Bedroom switch
    light.aeotec_zw098_led_bulb_level_4:
      friendly_name: Bedroom Floor Lamp

customize:
  light.hue_white_lamp_5:
    homebridge_hidden: true`

**Comment by nashlib** [comment]
sorry.

`homeassistant:
  customize:
    switch.aeotec_zw096_smart_switch_6_switch_2:
      friendly_name: Second Bedroom switch
    light.aeotec_zw098_led_bulb_level_4:
      friendly_name: Bedroom Floor Lamp

customize:
  light.hue_white_lamp_5:
    homebridge_hidden: true`

**Comment by maddox** [comment]
Your indention there looks off, be sure it's nested under the appropriate keys in the YAML. Also, is that in the same file. I'm not sure you can have 2 customize keys. Try this:

```yaml
homeassistant:
  customize:
    switch.aeotec_zw096_smart_switch_6_switch_2:
      friendly_name: Second Bedroom switch
    light.aeotec_zw098_led_bulb_level_4:
      friendly_name: Bedroom Floor Lamp
    light.hue_white_lamp_5:
      homebridge_hidden: true
```

**Comment by nashlib** [comment]
works like a charm !!!! - aweome buddy - thanks !!!!
