### ISSUE TITLE
Homebridge-homeassistant plugin not dropping socket connections when homeassistant restarted

### ISSUE THREAD

**Issue by terrycarlin** [home-assistant/homebridge-homeassistant#150]
Pi3/Raspbian:
When homeassistant is restarted, the plugin is not closing the old socket connections  This shows up when you are developing your hass configuration and have to restart homeassistant many times over a long time period.  I have seen almost 500 connections from the plugin to homeassistant and since there is two sockets used per connection, that was almost 1000 sockets opened and homeassistant got _really_ slow.  You can get around this issue by restarting homebridge everytime you restart homeassistant, but that is kind of a kludge. I am thinking that there should be some sort of a socket timeout when homeassistant goes away.

Steps to duplicate: 
1. have homebridge, homebridge-homeassistant, homeassistant running.
2. Do a netstat -a|grep 8123 and see the number of connections.
3. restart homeassistant.  Do not reboot the server.
4. Do a netstat -a|grep 8123 and see that the number of connections went up.

**Comment by robbiet480** [comment]
I'll most likely fix this when we migrate to using Websockets instead of SSE. Thanks for the report!
