### ISSUE TITLE
Homebridge stopping due to error in switch.js

### ISSUE THREAD

**Issue by Regularj** [home-assistant/homebridge-homeassistant#156]
The following error keeps appearing and stopping homebridge after a while (in combination with home-assistant - if that helps):

https://pastebin.com/vsAmHSiX

**Comment by robbiet480** [comment]
One of your entities is weird and doesn't have a state parameter. Not sure how to be more specific than that :(

**Comment by Regularj** [comment]
Solved. Selfmade error in the config.
