### ISSUE TITLE
Groups do not turn off lights.

### ISSUE THREAD

**Issue by CCOSTAN** [home-assistant/homebridge-homeassistant#158]
So the groups show up perfectly in HomeKit.  The initial states from HomeAssistant seem to match up but turning the group off in home kit does not turn off the actual lights. 

I have set the group as a switch or light and it doesn't matter.

**Comment by CCOSTAN** [comment]
No errors in the HomeBridge log..

**Comment by bachya** [comment]
I'm in the same boat. I have a group of lights exposed as a switch in Homebridge via this plugin, but can't turn the actual lights on or off via that switch.

**Comment by mathewpeterson** [comment]
I'm getting the same error @bachya. Any solutions for this yet?
