### ISSUE TITLE
add AirQuality

### ISSUE THREAD

**Issue by abcabcabcab** [home-assistant/homebridge-homeassistant#161]

**Comment by schmittx** [comment]
Can you give more info on which Home Assistant component you want to use this with?

I'm guessing [World Air Quality Index](https://home-assistant.io/components/sensor.waqi/)?

**Comment by abcabcabcab** [comment]
yes

**Comment by schmittx** [comment]
PR coming soon for this, I've got it working for my personal setup at the moment.
