### ISSUE TITLE
Nest thermostat doesn't appear correctly

### ISSUE THREAD

**Issue by bachya** [home-assistant/homebridge-homeassistant#163]
When I use the [homebridge-nest](https://www.npmjs.com/package/homebridge-nest) plugin, my Nest thermostat shows up fine:

![img_0543](https://cloud.githubusercontent.com/assets/47216/26518045/7995ead0-4264-11e7-96c6-27aeba263e10.PNG)

However, when I view the Nest thermostat as configured via Home Assistant, I get the following error:

![img_0542](https://cloud.githubusercontent.com/assets/47216/26518046/7cc764ea-4264-11e7-9c68-3b217d73f0da.PNG)

Unfortunately, the logs don't show any related errors.

**Comment by mastahype** [comment]
I get the same issue for my RadioThermostat, and looks like others also. It looks like climate isn't fully working, as I can't get homebridge to set my temperature either. I can see the request get to homeassistant, always in Celsius, but it never takes affect (I'm in Fahrenheit on the hass side). Homeassitant(hass) is able to correctly set and read my thermostat, so it's something to do with the bridge/plugin.

**Comment by mastahype** [comment]
So for me, this issue was directly related to the fact that homebridge-homeassistant plugin assumes Celsius for climate (likely based on the homekit internal representation [or old representation] - I'm not familiar with the history). Anyway, I put in two conversion methods for celsiusToFahrenheit and fahrenheitToCelsius and added to the get/setTargetTemp and getCurrentTemp in accessories/climate.js and my radiothermostat immediately started working from HomeKit. It read the temp and I was able to set it and have it engage. The Radiothermostat Homeassistant plugin assumes Fahrenheit for inputs - likely due to the ReST API it exposes. I am considering to make a configurable patch for climate.js so that you can override this for similar devices. HomeAssistant seems to handle C/F conversion already, so I think it's better to make this change in the homebridge-homeassitant plugin because it just assumes Celsius.

**Comment by robbiet480** [comment]
Can you test again with the new version I am about to publish? It will include the improvements from #178.

**Comment by AmpacheUser** [comment]
@mastahype I am having the same Issue with my RadioThermostat. Could I get a copy of your updated climate.js file?

**Comment by heathpitts** [comment]
Is this potentially why my Ecobee 3 thermostats show cooling to 162 degrees? I have the pre-HimeKit enabled ones so I'm using home Assistant to expose them to homebridge. I've tried changing the measurements but it doesn't make a difference.

**Comment by AmpacheUser** [comment]
@heathpitts Yea, same happens for me. Shows cooling to 172 Degrees.
It's obviously a Fahrenheit temperature that is being converted to Fahrenheit.
I am hoping @mastahype can get us a copy of his update climate.js to fix it.

**Comment by heathpitts** [comment]
Ok thanks. Will be awesome when this is fixed. This along with alarm panel support were the final pieces I was looking for with Homebridge-homeassistant.

**Comment by heathpitts** [comment]
Looks like this fix was left out of the newest 2.3.0 release as well. Maybe this will be fixed soon

**Comment by AmpacheUser** [comment]
Yes, hopefully on the next release. If I knew a bit more I would try to fix it myself in the climate,js.

**Comment by faspina** [comment]
Any update. I was wondering what was wrong with mine until I saw this thread. I am going to take a look at climate.js and see if I can figure it out

**Comment by mastahype** [comment]
@AmpacheUser, @faspina, I can post my changes ([posted here](https://pastebin.com/RKqaY1Gc)), but it's probably better to confirm the changes by @robbiet480 first. His changes from [#178](https://github.com/home-assistant/homebridge-homeassistant/pull/178) and more might address the issue entirely. I just haven't had the time to sync and test those changes myself.

**Comment by mceres** [comment]
After the new release of homeassistant-homebridge my nest show correct temperature but I am not able to change the temperature. I will give the hombridge-nest plugin a try.

**Comment by mastahype** [comment]
@mceres do you have any logs? You should be able to see what is being sent or received between homebridge-homeassistant and homeassistant.

**Comment by mceres** [comment]
This is what i see on the add-on page. Are there any other logs i should be looking at?

i am using homeassistant 0.56.2 and homebridge add-on 2.1.1

[2017-11-2 19:27:45] [HomeAssistant] fetching brightness for: Living Room
[2017-11-2 19:27:45] [HomeAssistant] fetching power state for: Living Room
[2017-11-2 19:27:45] [HomeAssistant] fetching Current Heating Cooling state for: Living Room (Living Room)
[2017-11-2 19:27:51] [HomeAssistant] Setting temperature on the 'Living Room (Living Room)' to 22.5
[2017-11-2 19:27:51] [HomeAssistant] Received event: {"event_type": "call_service", "data": {"domain": "climate", "service": "set_temperature", "service_data": {"entity_id": "climate.living_room_living_room", "temperature": 22.5}, "service_call_id": "140131611104648-120"}, "origin": "LOCAL", "time_fired": "2017-11-03T00:27:51.019964+00:00"}
[2017-11-2 19:28:01] [HomeAssistant] Successfully set temperature of 'Living Room (Living Room)'

**Comment by GraysonAdams** [comment]
I am having the same problem. I can view the temperature just fine, but attempting to change it through HomeBridge, it just times out.

If I try and set climate through Home Assistant, it works fine and immediately.

(Fahreinheit)

**Comment by CMaxim77** [comment]
Mine is still unfortunately not working (Nest Thermostat) if I add it to my Homebridge setup and expose it to my Home app it crashes every device that runs through Home Assistant. I hope eventually this gets fixed. I’m nowhere near talented enough to try to fix it myself.....
