### ISSUE TITLE
Is there a way to invert the functionality of homebridge_hidden: true?

### ISSUE THREAD

**Issue by mihalski** [home-assistant/homebridge-homeassistant#169]
Is it possible for all "accessories" to be ignored unless something like homebridge_visible: true (or similar) is used under customise?

When you have MANY accessories this would be FAR easier to manage than homebridge_hidden: true.

Regards,
Michal

**Comment by schmittx** [comment]
Completely agree with you...

**Comment by davle** [comment]
This works for me:

  customize_glob:
    "*":
      homebridge_hidden: true

then below

  customize:
    sensor.temp:
      homebridge_hidden: false

Since the order in the config file matters, and its possible to overwrite value this seems to work...

**Comment by schmittx** [comment]
I've got a PR coming to address this. You'll specify default default behavior in config.json (hidden or visible) and then customize each entity via HomeAssistant (if default is hidden, then you'd use HomeAssistant customize to specify which ones are visible to Homebridge; or vice versa).
