### ISSUE TITLE
Sporadic crashing after updating to 1.2.0

### ISSUE THREAD

**Issue by KmanOz** [home-assistant/homebridge-homeassistant#17]
Decided to upgrade to the latest ver yesterday. Has been running flawless for 3 months and am now getting crashes ever so often. Homebridge ver has stayed the same. Only plugin ver has changed and I'm running nothing but the homeassistant plugin. Latest message on screen was :

Verify Fail!
Layer Decrypt Fail!

Any clues as to what may be causing this.? It's running on a rock solid Debian install.

Kman

**Comment by KmanOz** [comment]
In light of no response and the fact that a new version has been released I will close this thread.

**Comment by maddox** [comment]
Sorry about that. Re-open this if you continue to have issues with the latest version.

**Comment by KmanOz** [comment]
Latest version hasn't crashed as yet. Will post something up if it does but doubt it because it would have happened by now. It was fairly regular with the previous ver.
