### ISSUE TITLE
gas binary sensor need to be added

### ISSUE THREAD

**Issue by uavana** [home-assistant/homebridge-homeassistant#173]
case 'smoke':
      return new HomeAssistantBinarySensor(log, data, client,
                                           Service.SmokeSensor,
                                           Characteristic.SmokeDetected,
                                           Characteristic.SmokeDetected.SMOKE_DETECTED,
                                           Characteristic.SmokeDetected.SMOKE_NOT_DETECTED);
    case 'gas':
      return new HomeAssistantBinarySensor(log, data, client,
                                           Service.CarbonMonoxideSensor,
                                           Characteristic.CarbonMonoxideDetected,
                                           Characteristic.CarbonMonoxideDetected.CO_LEVELS_ABNORMAL,
                                           Characteristic.CarbonMonoxideDetected.CO_LEVELS_NORMAL);

**Comment by schmittx** [comment]
This feature already exists as of the latest commit, make sure to set `device_class` to `gas` and `homebridge_gas_type` to `co` or `co2` (see the README).

@robbiet480 Can you update the package and publish to NPM with this latest commit?

**Comment by robbiet480** [comment]
@schmittx Will do shortly, closing this issue, re-open if you are still having problems
