### ISSUE TITLE
Flux_LED lights change to white on color change, then become unresponsive

### ISSUE THREAD

**Issue by Lethegrin** [home-assistant/homebridge-homeassistant#174]
This seems very similar to this issue here: https://github.com/home-assistant/home-assistant/issues/7814

After trying to change the color or brightness of a flux_led light, it will turn on it's dedicated white LEDs or simply turn white, and become unresponsive.

Not sure if this is a homebridge-homeassistant plugin issue or what. It seems to have been fixed in home assistant as the bug does not occur while using the home assistant UI directly.

**Comment by yoyor10** [comment]
I’m currently experiencing this problem too, any luck?

**Comment by schmittx** [comment]
Are you able to test #272? Does that fix your problem?

**Comment by yoyor10** [comment]
Hey there, the problem was solved with the last update of the hass.io firmware. It’s now functioning properly. Let me know if i can help with something😃

**Comment by schmittx** [comment]
Good, I'll close this issue then.

If you continue to have problems, please re-open.
