### ISSUE TITLE
Option to whitelist entities to Homebridge

### ISSUE THREAD

**Issue by Phontana** [home-assistant/homebridge-homeassistant#179]
I'd like an option for customize.yaml to whitelist entities, instead of blacklisting every item I don't want to see in HomeKit. I have more devices I want to hide than that I want to show, and every time I add a new entity it shows up in Homekit, even if I don't want it. Is it possible to add a flag like `homebridge_show: true` and a global flag to hide entities by default?

**Comment by rbhr** [comment]
Triple yes please!

**Comment by schmittx** [comment]
PR coming for this, check #169 comments.

**Comment by abcabcabcab** [comment]
![674bd1c4-d4ee-4bb0-9415-87fbe4589d60](https://user-images.githubusercontent.com/28006700/29072825-eb0db066-7c7b-11e7-8bc5-eb7034b554d5.png)
![c1f54c6e-3bc5-49bd-b07d-582842c0907b](https://user-images.githubusercontent.com/28006700/29072828-ec77c6c6-7c7b-11e7-97f5-1b025939adc9.png)
xiaomi Illumination Sensor and script

**Comment by robbiet480** [comment]
#169 is now merged, re-open if you're still having issues!
