### ISSUE TITLE
Fetching states to include brightness?

### ISSUE THREAD

**Issue by PollieKrismis** [home-assistant/homebridge-homeassistant#18]
I'm trying out Apple's new Home app. It seems to want the brightness in addition to the state.

Setting it from the Home app works fine. It is only when fetching the brightness when refreshing/updating the status that it is returned as 0% when the light is on. 

Is this because it incorrectly interprets toggle switches/lights as dimmers or because of the way they are exposed via the bridge? In Home Assistant they appear as simple toggle/binary switches.

Here is the last part of the log when opening the Home app and then using it to toggle a light.

`Jul 20 07:33:48 raspberrypi homebridge[2297]: [7/20/2016, 7:33:48 AM] [HomeAssistant] fetching brightness for: Eetkamer Tafellig
Jul 20 07:33:48 raspberrypi homebridge[2297]: [7/20/2016, 7:33:48 AM] [HomeAssistant] fetching power state for: Eetkamer Tafellig
Jul 20 07:34:48 raspberrypi homebridge[2297]: [7/20/2016, 7:34:48 AM] [HomeAssistant] Setting power state on the 'Ganglig' to on
Jul 20 07:34:48 raspberrypi homebridge[2297]: [7/20/2016, 7:34:48 AM] [HomeAssistant] Setting brightness on the 'Ganglig' to 100
Jul 20 07:34:48 raspberrypi homebridge[2297]: [7/20/2016, 7:34:48 AM] [HomeAssistant] Successfully set power state on the 'Ganglig' to on
Jul 20 07:34:48 raspberrypi homebridge[2297]: [7/20/2016, 7:34:48 AM] [HomeAssistant] Successfully set brightness on the 'Ganglig' to 100
Jul 20 07:35:00 raspberrypi homebridge[2297]: [7/20/2016, 7:35:00 AM] [HomeAssistant] Setting power state on the 'Ganglig' to off
Jul 20 07:35:01 raspberrypi homebridge[2297]: [7/20/2016, 7:35:01 AM] [HomeAssistant] Successfully set power state on the 'Ganglig' to off`

**Comment by robbiet480** [comment]
Closing in favor of #23 and #26. #23 has more information about why this happens. A fix has already been implemented in Home Assistant (home-assistant/home-assistant#2828) and will be available in 0.27.
