### ISSUE TITLE
My Nest Thermostat shows heating as status all the time even when cooling

### ISSUE THREAD

**Issue by ikifar2012** [home-assistant/homebridge-homeassistant#182]
My homebridge always shows heating but i can set it to cooling but in a few minutes it goes back to heating 
![image](https://user-images.githubusercontent.com/20800434/27995942-26d84622-64a5-11e7-8ec1-69d8a4077a25.png)

**Comment by robbiet480** [comment]
Can you test again with the new version I am about to publish? It will include the improvements from #178. Please re-open if you are still having issues.
