### ISSUE TITLE
2.2.0 General Homebridge failure!!

### ISSUE THREAD

**Issue by kalety** [home-assistant/homebridge-homeassistant#189]
Like I said in title: General Failure!!!, reverting to 2.10 and all went right!

**Comment by jcastro** [comment]
There's a bug open here already https://github.com/home-assistant/homebridge-homeassistant/issues/188

**Comment by kalety** [comment]
You'd said that fails your plugin, I said whooooole Homebridge falling down!

**Comment by jcastro** [comment]
No, in my case it breaks Homebridge

**Comment by robbiet480** [comment]
Closing in favor of #188, please search issues before opening a new one next time, thanks!
