### ISSUE TITLE
Alarm support planned?

### ISSUE THREAD

**Issue by PollieKrismis** [home-assistant/homebridge-homeassistant#19]
Any plans to also support Home Assistant alarms or is the idea that the goodnight scene in the Home/Homekit apps simply actives a similar scene in Home Assistant.

Not sure what other use cases there are, but the ultimate goal is to only expose Home Assistant to the Internet via Home/Homekit in order to piggyback on Apple's security between devices.

**Comment by robbiet480** [comment]
@PollieKrismis Sorry to take so long to respond. None of the primary authors of homebridge-homeassistant currently have an alarm panel so I don't expect any of us will be adding it but it's pretty easy to do yourself or for someone else to do.

**Comment by PollieKrismis** [comment]
@robbiet480 Thanks, I'll look into it once I get my PR's merged as I have quite a bit of work left on them.

**Comment by heathpitts** [comment]
Did you make any progress on the alarm panel?

**Comment by PollieKrismis** [comment]
@heathpitts no progress on this... My 2011 MacBook broke, Apple said they will fix it for free as part of a video recall program. We still waiting on the final approval to start the repair...

**Comment by funstuff234** [comment]
Also interested in this

**Comment by bandycj** [comment]
I'd be happy to help test this when work gets started.
