### ISSUE TITLE
Future feature requests wanted

### ISSUE THREAD

**Issue by schmittx** [home-assistant/homebridge-homeassistant#198]
I'm planning to work on the following features for the next release.

- Update climate for better support with Nest thermostats (testing help for other makes/models would be appreciated as I only have a Nest thermostat personally).
- Reduce usage/need for so many `homebridge_blah_blah` statements (more automated detection across all device types).
- Investigate HomeKit speaker service, add ability for media players to be exposed as speakers (if possible).

If you've got any other ideas, let's hear it!

Of course, if you find any problems let's hear about those too!

**Comment by andersonshatch** [comment]
Concerning climate, as I mentioned in #178, it would be nice to add a configurable map of HomeKit mode to hass mode, as there are other modes on some devices not just Auto/Heat/Cool/Off.
This could address #194, by allowing you to specify which mode "Auto" from HomeKit actually sets in hass. (Auto is a reasonable default for when you just ask Siri to set a temp, but I understand the desire to override it)

**Comment by Hackashaq666** [comment]
Good luck with the speaker service! Could be a great addition.

**Comment by schmittx** [comment]
@andersonshatch Good suggestion. I hadn't looked at your recent PR changes but now I see that you and I are on the same track.

@Hackashaq666 Bad news, apparently the iOS 10 Home app doesn't support speaker services yet (whyyyyy?!). Support is supposed to be added as part of iOS 11, so I'm going to put this on the back burner for a bit.

**Comment by fedor1210** [comment]
Ack support for not-optimistic devices. For example: if you turn on/off not responding MQTT device through homebridge, it will be shown as "not responding" after timeout.
