### ISSUE TITLE
Accessories disappearing from Home.app

### ISSUE THREAD

**Issue by eplt** [home-assistant/homebridge-homeassistant#201]
I have 6 accessories setup on homeassistant and all working fine via web interface.
When I first pair the homebridge with my home.app, it shows up all 6 accessories. They are 4 switches and 2 sensors.
After a while, one of the accessory will disappear. In no apparent order, just one of them, leaving 5 of them showing connected via the bridge. Sometimes, on iOS11 home.app, it shows a "Not Supported" status of one of the device.
Anyone else having this issue?
My solution for now is to only setup 5 devices in homeassistant, and that is stable.

**Comment by ikifar2012** [comment]
Me on my beta device 
 if you restart homebridge before home assistant has discovered devices thy will disappear but that is different issue but yes I have had the exact same thing on IOS 11

**Comment by eplt** [comment]
i am trying on both iOS11 beta and iOS10. both having similar issue. i have also tried restarting homebridge after home-assistant fully started with all devices. but it will still disappear after a while. the odd part is. the disappearing accessory is not in any particular order. and most of my devices are via mqtt broker, so there shouldn't be many discovery issues?
