### ISSUE TITLE
Notifications after Homebridge restart

### ISSUE THREAD

**Issue by heathpitts** [home-assistant/homebridge-homeassistant#202]
Is there any way to stop notifications from firing after a homebridge restart? Anything that I have setup for a notification from the Home app that is connected to homeassistant fires a notification when the home bridge service is restarted. Right now this is an alarm panel and a garage door opener.

**Comment by Hackashaq666** [comment]
This would be good sddition

**Comment by schmittx** [comment]
This is a Homebridge concern, not a plugin problem.
