### ISSUE TITLE
Initial speaker service support for media players, testers wanted

### ISSUE THREAD

**Issue by schmittx** [home-assistant/homebridge-homeassistant#215]
If anyone's interested, I've got a rough example of of the speaker service running. Just replace your media_player.js with the modified one below. This will create two services for the media player entity, one switch service to control play/pause/stop/on/off/etc. (like current behavior) and one additional speaker service.

Note that iOS 10 Home app does not support speakers (yet?), so you'll need to use a third party app. I'm currently testing with "Home" ([App Store link](https://itunes.apple.com/us/app/home-smart-home-automation/id995994352?mt=8)).

In Home Assistant, add `homebridge_speaker` to the desired media player entity and set to either `mute` or `volume`.

`mute` = mute on/off only
`volume` = mute on/off and volume control

Not all media players support these mute/volume functions. Furthermore some show that they do, even though the functions don't seem to work (i.e. Sony Bravia TV component?). So for now, play around with it if you want and let me know of any feedback.

Get the modified media_player.js [here](https://github.com/schmittx/homebridge-homeassistant/blob/development/accessories/media_player.js).

**Comment by maddox** [comment]
Why not push a branch up?

Also, I thought speaker support was part of iOS 11 HomeKit support, not just the iOS Home App. How does it work in the third party Home app?

**Comment by schmittx** [comment]
Yeah, I can push a branch up later tonight.

You're correct, HomeKit currently supports speakers but the iOS 10 Home app does not. I'm not sure about the iOS 11 Home app though, so I'm anxious to see if someone can test.

In the third party Home app (shown below), speakers show up as a switch for mute (on/off) and as a slider for volume (if enabled).

![img_1012](https://user-images.githubusercontent.com/630673/29575792-925d2dd0-8733-11e7-9049-8598267c872d.PNG)

![img_1013](https://user-images.githubusercontent.com/630673/29575793-926c5b02-8733-11e7-8e15-78aa01b7d2dd.PNG)

**Comment by schmittx** [comment]
Complete branch for those that want to test ([link](https://github.com/schmittx/homebridge-homeassistant/tree/speaker-service-test)).

**Comment by Blueforcer** [comment]
Where do I have to copy the file?

**Comment by schmittx** [comment]
@Blueforcer Copy the file or pull the branch into a local folder and run an instance of Homebridge from that location using the command shown [here](https://github.com/nfarina/homebridge#plugin-development).

**Comment by abcabcabcab** [comment]
ios11 home app still not

**Comment by abcabcabcab** [comment]
![049f06570117b5a13ef49c7d3010760e](https://user-images.githubusercontent.com/28006700/30708910-0990c732-9ec6-11e7-87cb-fdddb291f278.png)

**Comment by vswraith** [comment]
Is this working on iOS 11?

**Comment by schmittx** [comment]
@vswraith No, unfortunately not.
