### ISSUE TITLE
When change light brightness, light temporarily goes to 100%

### ISSUE THREAD

**Issue by boojew** [home-assistant/homebridge-homeassistant#218]
When controlling light switches/bulbs that allow for dimming, it temporarily sets the brightness to 100% (or perhaps send on?) and then the correct brightness. From within hass, I do not see this behaviour. Dimming functions correctly. I am not sure if this is a homebridge or add-on issue..

Version info 
npm info using npm@3.10.10
npm info using node@v6.11.0
avahi-daemon 0.6.32
Homebridge 0.4.25
Addon 2.3.1

For HomeAssistant, I am on 0.52.1 and the ISY component to control Insteon lights

**Comment by Hackashaq666** [comment]
I see the same behavior

**Comment by boojew** [comment]
What’s your environment like? What component are your lights?

**Comment by Hackashaq666** [comment]
I'm on windows 10. I keep homeassistant, homebridge and plugins up to date.
Lights are operated by lutron caseta dimmer switch connected to wink hub.

**Comment by boojew** [comment]
This may be related to https://github.com/nfarina/homebridge/issues/240
