### ISSUE TITLE
default_visibility: hidden not working

### ISSUE THREAD

**Issue by cjsmns** [home-assistant/homebridge-homeassistant#227]
So I've been using this for a while with my home-assistant setup on my pi3 for a few months now. It works great, and for the most part, just makes things so much easier.

For the last week or so, I've decided that I want to have the default visibilty set to hidden. I add a new device and groups, and then I have 20 new devices in my homekit. It's kinda annoying, so I'm trying the hidden router.

Unfortunalty it's not taking effect. Everything is still visible. I've removed all hide tags from my customize.yaml file, and rebooted and still everything is visible. I've even gone as far as to fully uninstall homebridge and this addon and still have the same thing happening.

Would this be a bug, or a mis-config or someting else entirely?

**Comment by cjsmns** [comment]
I think I worked it out. Seems that there is a bunch of files hiding in /var/homebridge and these were getting involved and causing havoc. I've since removed them, and fulling uninstalled hombridge again, and reinstalled, and it seems ok now.

Now I have no devices showing, even though I'm using the homebridge_visible: true tag.

**Comment by Tomfr06** [comment]
I have the same issue, the homebridge_homeassistant config.json global parameter works (hide all or show all)
But the homeassistant "customize" part does not work in either way (despite homeassistant developer tools reporting the proper attribute

Did you close the issue because you found a solution? would you share :-)?

**Comment by cjsmns** [comment]
the problem I had was that I had a , at the end of the very last line in the homebridge config. This extra comma was causing something to happen. As this last line in my config was the default_visibility parameter, and the last line of my config, the comma wasn't needed.

If you are having the same issue, double check your config for homebridge and double check all your commas at the end of each line. The last line does need a comma. Check the example config on the Readme.
