### ISSUE TITLE
Where do I find config.json

### ISSUE THREAD

**Issue by cmlittle** [home-assistant/homebridge-homeassistant#228]
Can you tell me where I can find the config.json file on a pi so that I can update the configuration? I don't see it in /usr/local/lib/node_modules/homebridge-homeassistant. I can't seem to find the file. Obviously I'm not familiar with the file structure for python packages in raspberry pi, so I apologize for the stupid question.

**Comment by CCOSTAN** [comment]
Should be /.homebridge
