### ISSUE TITLE
Sending a Command To a Device Using Siri Through HomeBridge

### ISSUE THREAD

**Issue by chigkim** [home-assistant/homebridge-homeassistant#230]
I got remote.harmony_hub to show up on my Home app using Home Bridge and Home Assistant.

I'd like to control my Fan connected to Harmony Hub using Siri.

Is there a way to set up so that I can say turn on/off Livingroom fan to Siri?

I would like to do it without relying on an activity because it will turn off devices on other activities and switch to fan activities when I launch the fan activity.

For example, if I was watching TV with watch tv activity, and if I launch the fan activity, it'll turn off tv and turn on the fan. Also if I power off, it'll turn off all the devices.

Is there a way to just send a command to a device on harmony hub using Siri without setting up an activity?

Thank you for your help!

**Comment by andersonshatch** [comment]
You could create an input_boolean switch for your fan in Home Assistant (make sure that it's exposed to HomeKit through this plugin so Siri can turn it on/off) and have an automation in Home Assistant triggered by that switch which will send a command from your Harmony Hub (by calling service `remote.send_command`)
If you need some help with implementing that I think posting on the [community forums](https://community.home-assistant.io) would be best.
