### ISSUE TITLE
Add brightness to Media Player devices to control volume

### ISSUE THREAD

**Issue by dhench** [home-assistant/homebridge-homeassistant#238]
Would it be possible to add volume control for media player devices?

Currently, Media Players are exposed as an on/off switch to HomeKit. Switching this over to a light or fan, would enable the option to turn the device on and off + control the intensity (ergo the volume of the device.).

**Comment by schmittx** [comment]
Yeah, this would be possible but I'm not sure if it'd be the best idea as it could be easily confused.

What's your usage situation? Stock iOS Home app? Using Siri or the actual app?

I ask because I'd rather utilize the HomeKit speaker service but it's not supported by the stock iOS Home app.

**Comment by maddox** [comment]
> Yeah, this would be possible but I'm not sure if it'd be the best idea as it could be easily confused.

This was specifically left out on purpose for just this reason.

**Comment by dhench** [comment]
Indeed, using the stock home app. Tried a homebridge plugin that supports the HomeKit speaker standard, but the lack of native integration (both Apple Watch and iPhone HomeKit app) was a dealbreaker. 

The usecase would be the opportunity to both turn on/off the television and control its volume from my wrist & phone.

Speaking of confusing, after installing the homebridge-homeassistant plugin, my television wouldn’t turn on or off using HomeKit, even though the commands did come trough in the terminal which was running homebridge at the time. Reading the documentation (which is might have skimmed over ;) ) I uncovered the default play/pause behaviour for media player devices. This behaviour is tremendously handy for devices such as a chromecast, but quite confusing for a non-play/pause device such as a television. Again, I should have red though all of the documentation, but I would have expected different default behaviour.

**Comment by scheeko** [comment]
With homebridge-ZP you can configure a speaker (Sonos) as a fan, with on/off + volume control. It works well with Home/Siri.

**Comment by schmittx** [comment]
As @maddox said, volume control via lightbulb service was left out on purpose to prevent confusion. Volume control via speaker service is the proper method (although it's not supported by the native Home app), I'm planning to introduce this functionality soon.

**Comment by smyrman** [comment]
@dhench, if you are interested, there is a pretty good example of how you can create a "fake light" for home-kit here:
- https://home-assistant.io/components/light.template/

This also allows you to use the on/off for mute. If you then have an "on/off" switch for e.g.`media_player.tv` and a light for `media_player.tv_volume`, the Siri/Home app integration should probably be quite decent.
