### ISSUE TITLE
Controlling AC fan speed 

### ISSUE THREAD

**Issue by honcheng** [home-assistant/homebridge-homeassistant#239]
It’s possible to control AC fan speed in Home Assistant, but I can’t seem to find a way to do that in Homebridge/HomeKit. Is there no way?

I’m wondering if it’s a good idea to set up a fan component for AC separately. So each AC will have a climate and fan component.

**Comment by robbiet480** [comment]
Was this fixed via #241?

**Comment by honcheng** [comment]
No. That’s for fan control. This is for fan in air conditioning, which I don’t think is supported by HomeKit

**Comment by honcheng** [comment]
Or maybe HomeKit does, but I have not seen homebridge support fan control in Aircon before

**Comment by honcheng** [comment]
Looks like it is possible after all. 
Added it here https://github.com/home-assistant/homebridge-homeassistant/pull/244

It is just a matter of adding a fan service to it, but in HomeKit the fan shows up as a separately linked accessory.

**Comment by honcheng** [comment]
PR merged
