### ISSUE TITLE
IP Camera Support

### ISSUE THREAD

**Issue by erfind** [home-assistant/homebridge-homeassistant#240]
Greetings! I was wondering if there would be any way that IP camera support would be added to this? I would love to have the IP cameras from Home Assistant be visible in my HomeKit Applications.

**Comment by shayshtern** [comment]
👍🏻👍🏻 Could be perfect

**Comment by robbiet480** [comment]
Not possible until Home Assistant supports RTP streaming of cameras. More info [here](https://github.com/KhaosT/HAP-NodeJS/wiki/IP-Camera).
