### ISSUE TITLE
Any Way to Import Cloudiness Into Homebridge?

### ISSUE THREAD

**Issue by erfind** [home-assistant/homebridge-homeassistant#254]
Hey All!

I'm looking for a way to use cloud cover as a sensor from Home Assistant into Homebridge.  I want to turn on our outside lights when there is 85% or more cloud cover.  Anyone know how to get this data from darksky or yr?

Thanks!

**Comment by schmittx** [comment]
There's no equivalent service or characteristic for cloud cover in HomeKit. The closest would be current ambient light level but that displays in lux, not percentage.

I'd recommend setting up the automation in Home Assistant rather than HomeKit.

**Comment by schmittx** [comment]
Closing this issue due to the limitations in HomeKit. If you want to revisit, please open a new issue.
