### ISSUE TITLE
MQTT Cover reports as open when unavailable

### ISSUE THREAD

**Issue by jjlawren** [home-assistant/homebridge-homeassistant#260]
When using an MQTT cover (https://home-assistant.io/components/cover.mqtt/) that becomes unavailable using ```availability_topic``` and ```payload_not_available```, the Homebridge representation always reports as open.

**Comment by schmittx** [comment]
This is the intent, as there is no "unknown" state within HomeKit. Therefore, we assume to be open for safety.
