### ISSUE TITLE
Alarm Night Arm workaround revisited

### ISSUE THREAD

**Issue by JAYMAN-ATX** [home-assistant/homebridge-homeassistant#261]
Is that Temporary workaround for "NIGHT_ARM" still required?

https://github.com/home-assistant/homebridge-homeassistant/pull/176/commits/01059c1e93ddb5ffbea3acee6dab2ff2753975e8

I can set my Manual Alarm Control Panel in Home Assistant to STATE_ALARM_ARMED_NIGHT just fine, and when I do so, it is also correctly reflected in HomeKit, but the other way doesn't work, since setting the state to NIGHT_ARM in HomeKit will be translated to 'alarm_arm_home' by Homebridge.

I see where it does that in the source code, but unfortunately I just got into Homebridge, so I have no idea how to make that change and test it.

**Comment by JAYMAN-ATX** [comment]
Ok, I think I learned that I need to create a pull request, so that's done.  Please review and approve if you're satisfied.

**Comment by schmittx** [comment]
Fixed by #262
