### ISSUE TITLE
I cant change colors through homekit properly

### ISSUE THREAD

**Issue by ollisier** [home-assistant/homebridge-homeassistant#265]
# Problem/Motivation

I need to be able to change colors from the home app but they don't change

## Expected behavior

When i pick a color over homekit it will change the color of the lamp

## Actual behavior

Only the first time i try to change the color from  my iphone after i have changed the color from home assistant does it update. It doesnt update the color on the Hassio web interface so it is something to do with the plugin, not the lights.

## Steps to reproduce

try changing colors of an rgb device

**Comment by schmittx** [comment]
Are you able to test #272? Does that fix your problem?
