### ISSUE TITLE
Feature Request: Expose HomeAssistant Video Sources through Homebridge

### ISSUE THREAD

**Issue by netmanchris** [home-assistant/homebridge-homeassistant#278]
Request for Video sources to be exposed through the homebridge. 

My use-case is specifically with the Ring Doorbell which is discovered through HomeAssistant properly and able to display video.  

According to the original homebridge Ring plugin ( https://www.npmjs.com/package/homebridge-platform-ring-video-doorbell ) the video can be exposed to homekit using the camera plugin (https://github.com/KhaosT/homebridge-camera-ffmpeg )

Please let me know what additional information I can send or provide. More than happy to provide testing feedback environment as well.

**Comment by mlowijs** [comment]
What if the camera itself exposes an RTSP feed? I’m using UniFi cameras for example, they are able to expose RTSP and RTMP feeds.

**Comment by schmittx** [comment]
Why not use a dedicated plugin for UniFi ([link](https://github.com/gozoinks/homebridge-camera-ffmpeg-ufv)) then?

From my understanding, Home Assistant API (which this plugin utilizes) doesn't expose RTSP streams.
