### ISSUE TITLE
"Arm Night" does "Arm Home" instead on manual alarm_control_panel component

### ISSUE THREAD

**Issue by GraysonAdams** [home-assistant/homebridge-homeassistant#279]
I would like to point out that this issue does not appear to be resolved, as the [previous issue suggests](https://github.com/home-assistant/homebridge-homeassistant/pull/262).

Pressing "Arm night" on the latest version for a manual alarm control panel component actually does "Arm home" and makes HomeKit bug out.

Is this fixable?

**Comment by schmittx** [comment]
Are you sure you're running the latest version of homebridge-homeassistant? If not, upgrade and then try again.

If so, then it's gotta be something with manual alarm control panel component within HASS or with how you've defined the alarm in the HASS config.

The current plugin works fine with my Honeywell TotalConnect alarm through HASS.

This plugin is pretty straightforward and simply calls the `alarm_arm_night` command, see line 117 of accessories/alarm_control_panel.js in this repo.

**Comment by JAYMAN-ATX** [comment]
That patch is not yet included in the latest distribution package. You have to modify the source file (accessories/alarm_control_panel.js) manually on your local server and restart homebridge to resolve the issue.

**Comment by schmittx** [comment]
@JAYMAN-ATX Ahh, good call...I didn't think to check that.

**Comment by schmittx** [comment]
New release is available in NPM now, please re-open or create a new issue if there's additional problems.
