### ISSUE TITLE
Climate should use supported_features from home-assistant

### ISSUE THREAD

**Issue by ciotlosm** [home-assistant/homebridge-homeassistant#281]
Climate should use supported_features from home-assistant to determine target_temperature modes and operation_modes

Currently when using Generic Thermostat for example you still get all operation modes (`auto`, `cool`, `heat`, `off`) even if you only have heater with `heat` and `off` available inside home-assistant.

**Comment by schmittx** [comment]
I agree, this should be part of the next release (along with multiple other updates for climate support)!
