### ISSUE TITLE
Mercedes Me in HA & Homebridge

### ISSUE THREAD

**Issue by markbajaj** [home-assistant/homebridge-homeassistant#286]
Hi, 

I have just added my Mercedes Me sensors to my Home Assistant, and cannot get them to show up in the home app. Nothing obvious from the logs either. Here is an excerpt  from my customise.yaml:

`sensor.fuel_level:
    friendly_name: Car Fuel
    homebridge_visible: true

binary_sensor.doors_closed:
   homebridge_visible: true

binary_sensor.doors_locked:
    homebridge_visible: true

sensor.fuel_range:
    homebridge_visible: true

sensor.next_service:
    homebridge_visible: true

sensor.odometer:
    homebridge_visible: true`

I haven't done anything fancy as just wanted to see them appear in the home app, then I was going to make them neater. Am I missing something obvious? Is it that these types of sensors are not supported? Can I 'cheat' it by say setting the type to one that is supported? EG fuel level is a % so could pretend it is a humidity sensor?

All other sensors and switches I have exposed appear fine.

**Comment by schmittx** [comment]
Check the README for [binary sensors](https://github.com/home-assistant/homebridge-homeassistant#binary-sensor-support) and [sensors](https://github.com/home-assistant/homebridge-homeassistant#sensor-support). This is all explained there.

**Comment by markbajaj** [comment]
Thanks for getting back to me.

I did take a look, but nothing I did seemed to work. I'll look again :(

**Comment by markbajaj** [comment]
I have sussed the binary sensors - I completely ignored the readme...even though I read it. I will continue adjusting the HA sensors to read the right output and this will fix it in HomeBridge. Thanks for pointing me to the obvious :)
