### ISSUE TITLE
New NPM release

### ISSUE THREAD

**Issue by remco770** [home-assistant/homebridge-homeassistant#293]
Is it possible to release a npm version? Last version release is 3.0.1 at 26 october 2017. There are many commits with fixes for issues

@schmittx 

Thanks!

**Comment by robbiet480** [comment]
This is my bad, i'll cut a new release right now

**Comment by robbiet480** [comment]
Released as 3.1.0.

@schmittx if you let me know what your username on npm is I'll give you publish access.

**Comment by schmittx** [comment]
@robbiet480 perfect!...it's easy, same as GitHub, "schmittx"

**Comment by robbiet480** [comment]
@schmittx done!

**Comment by schmittx** [comment]
Thanks!
