### ISSUE TITLE
No devices in "Home" while using system.d boot up method

### ISSUE THREAD

**Issue by chrisklpp** [home-assistant/homebridge-homeassistant#295]
I have two sources for homebridge: my Hue Bridge with Osram Plugs and Bulbs and one test device via Homa-Assistant. When i start homebridge manually using the "homebridge" command all devices are registered properly and appear in my "Home" App. When I'm running homebridge in standard operation via `systemctl start homebridge` only the Hue Devices appear.
I attached the logfile from the systemd start `(systemctl status homebridge)`. For a manual start additionally theses lines appear:
`[HomeAssistant] Fetching HomeAssistant devices.
[HomeAssistant] Received event: ping
[HomeAssistant] Initializing platform accessory 'anlage'...`
Additionally i appended my systemd startup script and my config.json.

I hope you can help me, I ask here because the homebridge devices added via the hue bridge are working.
Thank you very much for helping and providing this program.

[log_homebridge.txt](https://github.com/home-assistant/homebridge-homeassistant/files/1725491/log_homebridge.txt)
[systemd.txt](https://github.com/home-assistant/homebridge-homeassistant/files/1725505/systemd.txt)
[config.json.txt](https://github.com/home-assistant/homebridge-homeassistant/files/1725512/config.json.txt)

**Comment by schmittx** [comment]
I assume you're running on a Pi or other Linux machine?

If so, have you confirmed the config file you're referring to is the correct one?

Check the Wiki for Hoembridge, specifically the section about auto start with systemd ([link](https://github.com/nfarina/homebridge/wiki/Running-Homebridge-on-a-Raspberry-Pi#running-homebridge-on-bootup-systemd)).

Also, double check your config. When I downloaded your attachment it showed some errors.

You should validate with JSONLint.com ([link](https://jsonlint.com/)).

**Comment by chrisklpp** [comment]
The configurations were ok, but because my system was fresh anyway so I reinstalled all components and now it works fine. I think there were some permissions messed up.
Thanks for your answer.

**Comment by schmittx** [comment]
No problem, glad to hear it's all good now.
