### ISSUE TITLE
Have to push twice - updating

### ISSUE THREAD

**Issue by krrisztian** [home-assistant/homebridge-homeassistant#30]
When I want to turn something on or off (a switch mainly) it says updating first when I press it or just pull up the bottom bar on iOS 10. Updating with little circle next to it and after like 5 seconds the switch (the button) becomes "alive". So as with Siri, first when I tell her to turn off she says she didn't hear back and when I tell her again the same thing instantly, she can do it.

**Comment by robbiet480** [comment]
This may be fixed by #29 which I will hopefully get to tonight

**Comment by robbiet480** [comment]
@krrisztian #29 has been merged, install 1.6.0 and let me know if you still have this issue.

**Comment by krrisztian** [comment]
updated to 1.6.0 and nothing changed. maybe homebridge bug?

**Comment by jmesaunders** [comment]
I'm on 1.6.0 and I can confirm I'm experiencing similar issues.

**Comment by krrisztian** [comment]
Yeah for me the same even with the 1.6.0 so only if I don't use it for like half an hour or so.

**Comment by robbiet480** [comment]
Is this still an issue? Please re-open if it is.
