### ISSUE TITLE
MQTT Cover Tilt ( 0 - 100 % in Homekit )

### ISSUE THREAD

**Issue by yanovik** [home-assistant/homebridge-homeassistant#304]
Hi, I wonder if it is possible to establish not only open/close/stop, but also discrete tilt position (0-100) for mqtt cover. As for me Homekit button works only for 0 and 100, any value in range 1-99 is not accepted.

`cover:
  - platform: mqtt
    name: "DrapeBig"
    command_topic: "DrapeBig/TargetPosition/Set"
    state_topic: "DrapeBig/CurrentPosition/Status"
    retain: false
    payload_open: "0"
    payload_close: "100"
    payload_stop: "STOP"
    state_open: "open"
    state_closed: "closed"
    optimistic: false
    value_template: '{{ value.x }}'
    tilt_command_topic: 'DrapeBig/TargetPosition/TiltSet'
    tilt_status_topic: 'DrapeBig/CurrentPosition/TiltStatus'
    tilt_min: 0
    tilt_max: 100
    tilt_closed_value: 0
    tilt_opened_value: 100`

I'm using Hassio, Node-red, mosquitto on the same rpi3.

**Comment by schmittx** [comment]
Can you tell me what service call you use to set the discrete position?

**Comment by yanovik** [comment]
set_cover_tilt_position
I suppose I should use "set_cover_position" but it has no slider in UI, so I use tilt. It looks like i missed something?

**Comment by fquinto** [comment]
I think is not `set_cover_position` is `set_position_topic`
[Documentation Cover MQTT](https://www.home-assistant.io/components/cover.mqtt/#set_position_topic)

In your code, add:
`set_position_topic: "DrapeBig/TargetPosition/Set"`
