### ISSUE TITLE
Air Quality (BME680)

### ISSUE THREAD

**Issue by ferazambuja** [home-assistant/homebridge-homeassistant#314]
I'm using a BME680 with Home Assistant. However, the air quality information is not fed to homekit. Might have something to do with the way is being calculated on home assistant.

Does anyone know or have an example of air quality sensor working via home assistant to homebridge?

**Comment by ferazambuja** [comment]
never mind. I don't think it supports it.

**Comment by Plastefuchs84** [comment]
Hey, I'm trying, too. I'm curious if the problem has been solved.

**Comment by Plastefuchs84** [comment]
I found something. Unfortunately I have not tested it yet. Maybe you could give a feedback if it works.

https://github.com/trho/homebridge-bme680
