### ISSUE TITLE
Config.json to Home Assistant

### ISSUE THREAD

**Issue by doodoovane** [home-assistant/homebridge-homeassistant#315]
Hi everyone,

I'm new with Hass as I used to run homebridge alone for a few monthes. 
I was wondering if there is a way to make Home Assistant recongnize the accssories already added in the config.json file? Or a simpler way to do this maybe.

Thank you for your help

Edit: In fact, i'm searching to connect both toggles in Hass and in Homekit. Maybe it's more specific like that

**Comment by maddox** [comment]
It's not clear what you mean. Do you mean you want Home Assistant to see the accessories you have in HomeKit? If so, sorry, this project does nothing but bridge your existing Home Assistant components to HomeKit.

**Comment by doodoovane** [comment]
Ok so if I understand, I've got first to setup my accessories in homeassistant then I will get them on Homekit?

**Comment by maddox** [comment]
Yes, that's the whole point. This project bridges all of your Home Assistant devices over to HomeKit.

You do all your devices and automations in Home Assistant, then add this plugin to Homebridge, and voila, everything is on HomeKit.

**Comment by doodoovane** [comment]
Perfect! Thank you, I was  doing it in the wrong way....

**Comment by maddox** [comment]
👍 👍 👍
