### ISSUE TITLE
[HomeAssistant] Failed getting devices: Error: connect ECONNREFUSED 192.168.1.101:8123. Retrying...

### ISSUE THREAD

**Issue by arlubu** [home-assistant/homebridge-homeassistant#317]
After I inserted the code below in config.json , I got the error as shown in the picture, anyone can help?

![2018-05-08 8 36 57](https://user-images.githubusercontent.com/39116564/39801993-7d104aa0-539f-11e8-8f9a-e1adb7706bfd.png)

{
  "bridge": {
    "name": "Home Assistant",
    "username": "B8:27:EB:42:67:6B",
    "port": 51826,
    "pin": "903-04-303"
  },
  "description": "Homebridge for Home Assistant",
  "accessories": [],
  "platforms": [
    {
      "platform": "HomeAssistant",
      "name": "HomeAssistant",
      "host": "http://192.168.1.101:8123/",
      "password": "",
      "default_visibility": "visible",
      "supported_types": [
        "automation",
        "binary_sensor",
        "climate",
        "cover",
        "device_tracker",
        "fan",
        "group",
        "input_boolean",
        "light",
        "lock",
        "media_player",
        "remote",
        "scene",
        "script",
        "sensor",
        "switch",
        "vacuum"
      ],
      "logging": true,
      "verify_ssl": false
    }
  ]

}

I have installed home bridge, home assistant, and also homebridge-homeassistant plugins, and they both work properly separately.

**Comment by schmittx** [comment]
Home Assistant is refusing the API connection. Do you have a password set within Home Assistant `http` ([documentation](https://www.home-assistant.io/components/http/))? Your Homebridge config shows no password...
