### ISSUE TITLE
Light sensor: home assistant passes type "lm" which doesn't match type "lux"

### ISSUE THREAD

**Issue by xcray** [home-assistant/homebridge-homeassistant#320]
And then it will not appears on HomeKit (homebridge), although it's quite fine inside home assistant.
Modify:
Line 173 of lib/node_modules/homebridge-homeassistant/accessories/sensor.js:
change to:
`(data.attributes.unit_of_measurement.toLowerCase() === 'lux'|| data.attributes.unit_of_measurement.toLowerCase() === 'lm')`
from:
`data.attributes.unit_of_measurement.toLowerCase() === 'lux'`
then it's ok.
Some components of ha use "lm" as the unit of measurement (for example, xiaomi_gateway) while others maybe use "lux".

**Comment by schmittx** [comment]
I recommend you check out the native [HomeKit](https://www.home-assistant.io/components/homekit/) component for Home Assistant. It currently supports both `lm` and `lux` units, and requires less setup than `homebridge-homeassistant`.

**Comment by xcray** [comment]
@schmittx Thanks for your advice, It's time for me to learn about HomeKit component. :-)
The reasons for me to use Home-bridge now:
1. HA doesn't support Xiaomi gateway's alarm control, which I think is important. On Home-bridge, it's ok.
2. This homebridge-homeassistant is developed by hass "officially".
3. Cameras (rtsp with ffmpeg) could be integrated to HomeKit via Homebridge.
4. Most important, I'am just newbie to HA, less understanding about many components.

**Comment by schmittx** [comment]
Not a problem. FYI, you can use the HASS native component (for HASS entities) and Homebridge (for other plugins) in parallel. You'd end up with two "bridges" (one for HASS and one for Homebridge) within HomeKit.

In regards to your comments:
1. If it's a bug, can you submit an issue in the HASS repo? If it's a feature request, then create a new topic in the forums. Then we can work on getting it resolved as the goal is to deprecate the `homebridge-homeassistant` plugin and encourage everyone to use the native component.
2. The HomeKit component is also developed "officially" by HASS members (including me), we've been working to duplicate the functionality of `homebridge-homeassistant` into the native component.
3. Camera support has already been suggested for the native component. It's on the roadmap but still needs more development.
4. I understand that one completely. Read through the [docs](https://www.home-assistant.io/components/homekit/) for the component and ask questions in the forums if you need help configuring. It's actually much easier to setup than Homebridge in my opinion.
