### ISSUE TITLE
Only able to select 2 fan speeds when I have 3 in Home Assistant.

### ISSUE THREAD

**Issue by ghost** [home-assistant/homebridge-homeassistant#321]
Hi, In Home Assistant I have set up a fan with three speed which are Low, Medium and High. Unfortunately in homebridge-homeassistant in the home app I only have the option to select 50% or 100% and they both just set the fan to high. I am not sure if this is a bug or I have done something wrong. Thank you.

**Comment by UserNAMEPersonThingy** [comment]
Here is my configuration for the fan:
```
fan:
  - platform: template
    fans:
      study_fan:
        friendly_name: "Study Fan"
        value_template: "{{ states('light.study_fan_state_light') }}"
        speed_template: "{{ states('input_select.study_fan_speed') }}"
        turn_on:
          service: light.turn_on
          data_template:
            entity_id: >
              {% if speed == 'High' %}
                light.study_fan_high_light
              {% elif speed == 'Medium' %}
                light.study_fan_medium_light
              {% elif speed == 'Low' %}
                light.study_fan_low_light
              {% else %}
                light.study_fan_low_light
              {% endif %}
        turn_off:
          service: script.study_fan_off
        set_speed:
          service: light.turn_on
          data_template:
            entity_id: >
              {% if speed == 'High' %}
                light.study_fan_high_light
              {% elif speed == 'Medium' %}
                light.study_fan_medium_light
              {% elif speed == 'Low' %}
                light.study_fan_low_light
              {% else %}
                light.study_fan_low_light
              {% endif %}
        speeds:
          - 'High'
          - 'Medium'
          - 'Low'
```

**Comment by schmittx** [comment]
What does the fan entity look like in Home Assistant? Does it show all 3 speeds and do all 3 speeds function as intended within Home Assistant?

**Comment by UserNAMEPersonThingy** [comment]
Yes, In Home Assistant I am able to select Low, Medium and High and it functions as intended.
![img_0124](https://user-images.githubusercontent.com/26513182/41747207-7b83b302-75f0-11e8-9cc4-8faeac2fbe88.jpeg)

**Comment by schmittx** [comment]
I haven't dug into this too much, but try inverting your `speed_list` definition:

```yaml
speeds:
  - 'Low'
  - 'Medium'
  - 'High'
```
Can you also paste a screenshot of the states/attributes screen for this entity?

**Comment by UserNAMEPersonThingy** [comment]
I tried inverting my speed list but that didn’t work. Here is a screenshot of the services/attributes:
![img_0125](https://user-images.githubusercontent.com/26513182/41763637-19f873be-7642-11e8-8853-6e2215379168.jpeg)
