### ISSUE TITLE
Add positioning and improved rollershutter support

### ISSUE THREAD

**Issue by nunofgs** [home-assistant/homebridge-homeassistant#33]
Since we now have position in HomeAssistant for z-wave rollershutters, is it possible to switch the blinds "GarageDoor" implementation to a [WindowCovering](https://github.com/KhaosT/HAP-NodeJS/blob/6b18907afbda9eeaeef27eabfe22c35d901db1da/lib/gen/HomeKitTypes.js#L2423)?

This would allow for positioning like: "close my shutter to 30%"

**Comment by robbiet480** [comment]
Closing this because `rollershutter` is deprecated and is being removed in 0.32. Instead, we have a few `cover` related PRs which will accomplish this, such as #55.
