### ISSUE TITLE
Failed getting devices: Error: certificate has expired

### ISSUE THREAD

**Issue by Yannik25** [home-assistant/homebridge-homeassistant#50]
Hallo, i have following issue:

```
Okt 07 12:19:33 raspberrypi homebridge[571]: [2016-10-07 12:19:33] [HomeAssistant] Fetching HomeAssistant devices.
Okt 07 12:19:33 raspberrypi homebridge[571]: [2016-10-07 12:19:33] [HomeAssistant] Failed getting devices: Error: certificate has expired. Retrying...
```

it just happens, when auto starting homebridge with systemd on raspberry.
I don't get the the error when starting Homebridge by typing: homebridge

my configuration looks like this

```
{
  "bridge": {
    "name": "Homebridge",
    "username": "CC:22:3D:E3:CE:30",
    "port": 51826,
    "pin": "031-45-154"
  },
  "platforms": [
    {
      "platform": "HomeAssistant",
      "name": "HomeAssistant",
      "host": "http://myhomeassistantip:8123",
      "password": "mypassword",
      "supported_types": ["fan", "garage_door", "input_boolean", "light", "lock", "media_player", "rollershutter", "scene", "switch"]
    }
  ]
}
```

**Comment by DTO213** [comment]
same issue,any solutions?

**Comment by robbiet480** [comment]
1. Please get a new certificate with a valid expiry date
2. [This section of the readme](https://github.com/home-assistant/homebridge-homeassistant#using-with-self-signed-ssl-certificates)

**Comment by DTO213** [comment]
Thank you so much!

**Comment by HFeenstra** [comment]
@robbiet480 I have the same issue as above. I did the export NODE_TLS_REJECT_UNAUTHORIZED=0 command and run homebridge again, still do I get the same error as above.
What do I do more wrong?

**Comment by robbiet480** [comment]
@HFeenstra your certificate is expired?
