### ISSUE TITLE
When using this module for homebridge no devices appair.

### ISSUE THREAD

**Issue by viperthepala** [home-assistant/homebridge-homeassistant#51]
As the title claims i dont get any devices registering.
Output for homebridge below

*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
[10/10/2016, 10:08:38 AM] Loaded plugin: homebridge-homeassistant
homebridge API version: 2
[10/10/2016, 10:08:38 AM] Registering platform 'homebridge-homeassistant.HomeAssistant'
[10/10/2016, 10:08:38 AM] ---
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:

    ┌────────────┐
    │ 031-45-154 │
    └────────────┘

[10/10/2016, 10:08:42 AM] Homebridge is running on port 51826.

Config as follow

{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },

    "platforms": [
        {
            "platform": "HomeAssistant",
            "name": "HomeAssistant",
            "host": "http://10.0.1.3:8123",
            "password": "********",
            "supported_types": ["light", "switch", "media_player"]
        }
    ]
}

**Comment by viperthepala** [comment]
using the following setup the all in one installer version.
Wich is updated to 0.30.1

**Comment by gonzalezcalleja** [comment]
This is working with my roller shutters with HA 0.30.1 

@viperthepala check your config.json, you have to enable un supported_types the new accessory "cover" (replace roller shutter)

**Comment by viperthepala** [comment]
but lights, media_players and such arnt working eighter.
currently edited "supported_types": ["light", "switch", "media_player", "scene", "rollershutter"] to "supported_types": ["light", "switch", "media_player"]
still nothing appairing.

**Comment by robbiet480** [comment]
All of these accessory types are working fine for me and my config looks similar to yours. Please try running `DEBUG=* homebridge -D` to enable debug logging and re-open this issue if you continue having problems.
