### ISSUE TITLE
Add device_tracker entities

### ISSUE THREAD

**Issue by Bart274** [home-assistant/homebridge-homeassistant#56]
Hi,

I would love it if you could add support for device_tracker entities.
I found this plugin: https://github.com/PeteLawrence/homebridge-people
It checks for people at home by scanning the network and it adds them as an OccupancySensor.
Maybe we can do the same for device_tracker entities?

**Comment by robbiet480** [comment]
idk, homebridge-people kinda abuses `OccupancySensor` to accomplish this.

**Comment by Bart274** [comment]
Yeah, but aren't we kinda abusing switches to add our media players to homekit?
