### ISSUE TITLE
Change color of lights

### ISSUE THREAD

**Issue by silverWeaver** [home-assistant/homebridge-homeassistant#57]
Is it possible to change the color of the lights?
From the documentation I understood that it's not, so here's a welcoming addition..

**Comment by MaKin211** [comment]
I'd also highly appreciate that. When setting up my MiLight bulbs in home bridge as accessories it works but then HA won't receive state changes and it messes up the automations. :/

**Comment by robbiet480** [comment]
Currently, this has been deemed impossible due to problems in converting the Home Assistant RGB colors to the HomeKit-expected colors. Closing this issue as such.

For more information please see #11

**Comment by noogie1** [comment]
I've just upgraded to the latest homebridge-homeassistant and notice I now have colour options in homebridge - however changes I make don't get pushed to my milight bulbs - is this still deemed impossible or is my setup wrong? :)

**Comment by robbiet480** [comment]
@tobre6 ?

**Comment by tobre6** [comment]
@noogie1 is color picking works with HA? If yes, then which are the attributes of the entity.

**Comment by noogie1** [comment]
@tobre6 Colour picking works in HA, and if I leave the Home app open on the colour wheel for the bulb and adjust the colour in HA I can see the centre colour update, but when I try and pick a colour from the iOS colour wheel the changes don't get pushed to HA or the bulb.

How do I find the attributes of the entity? (Sorry, I'm still relatively fresh to Home-Assistant! :)

**Comment by tobre6** [comment]
@robbiet480 Please apply as soon as possible this hotfix: https://github.com/home-assistant/homebridge-homeassistant/pull/116

**Comment by noogie1** [comment]
@tobre6 - Applied your fix to my light.js and it fixed the Issue. Thank you so much!

**Comment by robbiet480** [comment]
Fixed in d662b7d09f287aebb8b14ff039caaf90f52795e2.
