### ISSUE TITLE
Unable to add Cover: Garage Door

### ISSUE THREAD

**Issue by oriolism** [home-assistant/homebridge-homeassistant#59]
I have a Garage Door Opener(ESP8266 E12 + MQTT) in my Home Assistant server. I read about the Cover support but Im unable to add the Garage Door to homebridge. 
In configuration.yaml i add this:
customize:
  cover.garage:
    homebridge_cover_type: garage_door

In homebirdge/config.json:
"platforms": [
  {
    "platform": "HomeAssistant",
    "name": "HomeAssistant",
    "host": "http://192.168.0.19:8123",
    "password": "XXXXX",
    "supported_types": ["input_boolean", "garage_door", "cover", "fan", "light", "lock", "media_player", "scene",$
  }

When hombridge is running i can see my Home Asssistant devices but no the Garage Door. Im missing something?

Regards,

**Comment by jsg4** [comment]
I see the same thing. Also the new device types do not show for me like cover, sensor, binary sensor

**Comment by robbiet480** [comment]
You need to upgrade to the latest (unreleased) version: `npm install -g home-assistant/homebridge-homeassistant`

**Comment by jsg4** [comment]
@robbiet480 

Now seeing this error. 

/usr/local/lib/node_modules/homebridge-homeassistant/accessories/cover.js:28
    throw new Error("You must provide the `homebridge_cover_type\" property " +
    ^

Error: You must provide the `homebridge_cover_type" property in the customise section of your Home Assistant config. Set it to either `rollershutter" or `garage_door".
    at Object.HomeAssistantCover (/usr/local/lib/node_modules/homebridge-homeassistant/accessories/cover.js:28:11)
    at /usr/local/lib/node_modules/homebridge-homeassistant/index.js:193:23
    at Request.onResponse [as _callback] (/usr/local/lib/node_modules/homebridge-homeassistant/index.js:111:7)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-homeassistant/node_modules/request/request.js:186:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-homeassistant/node_modules/request/request.js:1060:10)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-homeassistant/node_modules/request/request.js:980:12)
    at IncomingMessage.g (events.js:260:16)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at nextTickCallbackWith2Args (node.js:437:9)
    at process._tickCallback (node.js:351:17)

Here is the customize file with the covers.

cover.bedroom_level_18_0:
  friendly_name: Bedroom Shades
  homebridge_cover_type: rollershutter

cover.bedroom_level_19_0:
  friendly_name: Bathroom Shades
  homebridge_cover_type: rollershutter

cover.window_1_level_12_0:
  friendly_name: Window 1
  homebridge_cover_type: rollershutter

cover.window_2_level_13_0:
  friendly_name: Window 2
  homebridge_cover_type: rollershutter

cover.window_3_level_14_0:
  friendly_name: Window 3
  homebridge_cover_type: rollershutter

cover.window_4_level_15_0:
  friendly_name: Window 4
  homebridge_cover_type: rollershutter

cover.window_5_level_16_0:
  friendly_name: Window 5
  homebridge_cover_type: rollershutter

cover.window_6_level_17_0:
  friendly_name: Window 6
  homebridge_cover_type: rollershutter

**Comment by oriolism** [comment]
With the latest version im getting this error:

[10/28/2016, 5:21:33 PM] [HomeAssistant] Fetching HomeAssistant devices.
Plugin - DidFinishLaunching
/usr/lib/node_modules/homebridge-homeassistant/accessories/cover.js:28
    throw new Error("You must provide the `homebridge_cover_type\" property " +
    ^

Error: You must provide the `homebridge_cover_type" property in the customise section of your Home Assistant config. Set it to either `rollershutter" or `garage_door".
    at Object.HomeAssistantCover (/usr/lib/node_modules/homebridge-homeassistant/accessories/cover.js:28:11)
    at /usr/lib/node_modules/homebridge-homeassistant/index.js:193:23
    at Request.onResponse [as _callback] (/usr/lib/node_modules/homebridge-homeassistant/index.js:111:7)
    at Request.self.callback (/usr/lib/node_modules/homebridge-homeassistant/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/usr/lib/node_modules/homebridge-homeassistant/node_modules/request/request.js:1060:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-homeassistant/node_modules/request/request.js:980:12)


In the configuration.yaml i have this:

customize:
cover.garage:
homebridge_cover_type: garage_door

and this:

cover:
  - platform: mqtt
    state_topic: "GarageDoor/Status"
    command_topic: "GarageDoor/Toggle"
    name: "garage"
    qos: 0
    retain: false
    payload_open: "OpenGarageDoor"
    payload_close: "CloseGarageDoor"
    payload_stop: "OpenGarageDoor"
    state_open: "DoorOpened"
    state_closed: "DoorClosed"
    optimistic: false
    value_template: '{{ value.x }}'

Do i need to change something?

**Comment by jsg4** [comment]
Lol

**Comment by robbiet480** [comment]
Neither of your configurations were properly indented. Was that because of GitHub or are they actually not indented?

Try this:

1. Open your frontend in your browser.
2. Change the end of the URL to be `/api/states?api_password=<your password>` where `<your password>` is the password you use to login to the frontend.
3. Find the cover entity_id in the output (it may help to paste the entire output into [JSONLint](http://jsonlint.com)
4. Confirm that you see `homebridge_cover_type` in the output.

If you don't see it, remember that you need to restart Home Assistant for any change to customize.

**Comment by jsg4** [comment]
It's because of Github. I see cover there. Here's an example 

"last_updated": "2016-10-29T00:08:36.164616+00:00", "state": "off"}, {"attributes": {"emulated_hue": true, "friendly_name": "Bedroom Shades", "homebridge_cover_type": "rollershutter", "node_id": 18}, "entity_id": "cover.bedroom_level_18_0", "last_changed": "2016-10-28T21:18:48.604639+00:00", "last_updated": "2016-10-28T21:18:48.604639+00:00", "state": "unknown"}, {"attributes": {"entity_picture":

**Comment by robbiet480** [comment]
Okay. Will investigate.

**Comment by robbiet480** [comment]
Fix pushed. Run `npm install -g home-assistant/homebridge-homeassistant` and let me know.

I didn't actually find a problem with the `cover_type` customize stuff but I did find a bigger issue which would cause a crash once you got past the original problem

**Comment by oriolism** [comment]
@jsg4 What file is suppose to have this configuration? Looks like im missing this.

{
  "attributes": {
    "emulated_hue": true,
    "friendly_name": "Bedroom Shades",
    "homebridge_cover_type": "rollershutter",
    "node_id": 18
  },
  "entity_id": "cover.bedroom_level_18_0",
  "last_changed": "2016-10-28T21:18:48.604639+00:00",
  "last_updated": "2016-10-28T21:18:48.604639+00:00",
  "state": "unknown"
}

**Comment by robbiet480** [comment]
@jsg4 Your `customize` section is supposed to have `homebridge_cover_type`. See the [README.md](https://github.com/home-assistant/homebridge-homeassistant#customization) and [Home Assistant documentation](https://home-assistant.io/getting-started/customizing-devices/) for more info.

**Comment by oriolism** [comment]
I have that in the custumize section but when I check with this /api/states?api_password=<your password>  i dont see it on the output.

**Comment by robbiet480** [comment]
@oriolism you restarted after adding it to `customize`?

**Comment by oriolism** [comment]
Yes

**Comment by robbiet480** [comment]
@oriolism Try `npm install -g home-assistant/homebridge-homeassistant` again because it will now output logs showing you which devices are missing it.

For your specific issue it's a problem with Home Assistant not homebridge-homeassistant.

**Comment by oriolism** [comment]
[10/30/2016, 10:56:15 AM] [HomeAssistant] 'cover.garage_door' is a cover but does not have a 'homebridge_cover_type' property set. You must set it to either 'rollershutter' or 'garage_door' in the customize section of your Home Assistant configuration. It will not be available to Homebridge until you do. See the README.md for more information. The attributes that were found are: {"friendly_name":"Garage Door"}

It looks like this doesn't work with the Cover mqtt devices. If i add the old mqtt Garage door platform i can see on homebridge but can't control it because its deprecated. 

garage_door:
  platform: mqtt
  state_topic: "home-assistant/garage-door"
  command_topic: "home-assistant/garage-door/set"
  name: "Garage Door"
  optimistic: false
  qos: 0
  retain: false
  state_open: "STATE_OPEN"
  state_closed: "STATE_CLOSED"
  service_open: "SERVICE_OPEN"
  service_close: "SERVICE_CLOSE"
  value_template: '{{ value.x }}'

**Comment by oriolism** [comment]
@robbiet480 I know the issue is close but isn't fixed for me. It looks like this is not working for the mqtt platform on HA. I already open an issue on Home Assistant but none has answer. I notice that you are a member of HA could you give me a hand with this? Thanks in advance!

**Comment by robbiet480** [comment]
@oriolism I would help you but I don't have any covers. Will try to find a developer who does and can assist. Can you link the issue you opened her?

**Comment by oriolism** [comment]
This is the issue I open:
https://github.com/home-assistant/home-assistant/issues/4129

For troubleshooting purposes you don't have to have the cover, you can add the configuration and it will appear on HA. 

Regards,
