### ISSUE TITLE
Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory

### ISSUE THREAD

**Issue by jsg4** [home-assistant/homebridge-homeassistant#60]
Also seeing this in latest version. Probably related to all of my sensors? I am running 0.31.1 in HA.

http://pastebin.com/RkDW0Gy9

**Comment by jsg4** [comment]
Never mind, fixed it with homebridge_hidden: true and homebridge_name:

**Comment by robbiet480** [comment]
This was fixed by #54, at least temporarily.
