### ISSUE TITLE
Cover component reporting incorrectly when Open

### ISSUE THREAD

**Issue by KmanOz** [home-assistant/homebridge-homeassistant#68]
Cover component reports closed when door is actually open. Cover Type is set to 

`'homebridge_cover_type: garage_door'`

When I push Garage Door button on Home app when the door is Closed (state confirmed in HA) as the door begins to open the Home app changes from CLOSED to OPENING... When the door has opened (state confirmed in HA) Home App displays CLOSED.

Push button again and door starts to close (even though it displays CLOSED) but Home App displays Opening... (because it thinks it was closed) until it actually closes and then changes to Closed. So either condition is CLOSED.

All my automations are working correctly in HA so it's not a HA issue.

***** UPDATE *****

Further to this I have discovered that if you close Home App or control panel favorites, and re-open (forcing an update) it after the door is confirmed OPEN it reports the door correctly as OPEN. So effectively it changes from CLOSED to OPEN on update but not when you initially push the key so in effect you need to do it twice. Also the notification from Home App says Garage Door is Closed, when it opens. There is something wrong with the logic somewhere.

Thanks

**Comment by robbiet480** [comment]
Did upgrading to the latest version with the fixes in #73 applied help this at all? If not, please reopen.
