### ISSUE TITLE
Negative temperature not reported

### ISSUE THREAD

**Issue by TWilb** [home-assistant/homebridge-homeassistant#71]
I have a temperature sensor reporting °C values. During the last night I got a value below 0°C and it was correctly handled in HA. Unfortunately this did not work with homebridge.

I could fix this by adding the following lines to sensors.js getServices():

```
this.sensorService
      .getCharacteristic(this.characteristic)
      .setProps({minValue: -50});
```

With -50°C I should be on the save side.

I am not sure if this is a good fix but for me it is working.

**Comment by hhalibo** [comment]
Thanks! I solved the same problem with your script!

**Comment by jamieshaw** [comment]
Confirmed that I'm having the same issue. Any value below 0ºc reports as "No Response" in HomeKit.

**Comment by landerss0n** [comment]
Confirmed, same issue here

**Comment by kirichkov** [comment]
I can also confirm the issue.

**Comment by krrisztian** [comment]
Also confirmed:(

**Comment by nodomain** [comment]
Please fix it :)

**Comment by nodomain** [comment]
Moreover, this fix did not help me - all other sensors report 0°C then.

**Comment by nodomain** [comment]
Please show me the complete code, I think the file has changed.

**Comment by TWilb** [comment]
@nodomain The file is still the same, it wasn't changed since commit e10a501 on 29 Oct 2016. Try inserting it in line 105.
What other sensors make problems afterwards?

**Comment by nodomain** [comment]
What exactly shall be added where?
```javascript
 getServices() {
    this.sensorService = new this.service();
    var informationService = new Service.AccessoryInformation();

    informationService
      .setCharacteristic(Characteristic.Manufacturer, "Home Assistant")
      .setCharacteristic(Characteristic.Model, "Sensor")
      .setCharacteristic(Characteristic.SerialNumber, this.entity_id);

    this.sensorService
      .getCharacteristic(this.characteristic)
      .on('get', this.getState.bind(this));

    return [informationService, this.sensorService];
  }

```

**Comment by jamieshaw** [comment]
@nodomain It's an entirely new line.  Your final code should look like the following:
```
this.sensorService
      .getCharacteristic(this.characteristic)
      .setProps({minValue: -50})
      .on('get', this.getState.bind(this));
```

If I can get the hang of git, merge requests and such, I'll put forward as a fix.

**Comment by nodomain** [comment]
Uh, my bad. Seems to work, at least reporting 1°, let's see what happens if the temp falls below zero ;)

**Comment by jamieshaw** [comment]
@nodomain Update the state through Home Assistant. If you catch it fast enough before it populates with the latest data, you can see if it's working 😉

**Comment by nodomain** [comment]
Yay, works 😀

**Comment by nodomain** [comment]
@jamieshaw filed it, also my first PR ;-)
