### ISSUE TITLE
missing sensors 

### ISSUE THREAD

**Issue by duecedriver** [home-assistant/homebridge-homeassistant#74]
after much installation woes and setting up avahi.. 

it is working.. and importing lights and a couple scenes....

I have binary sensors setup in the home assistant son

in home assistant I defined a binary sensor for a smoke detector and set its class to smoke but its not showing up

I have tried deleting persists
i have restarted numerous times
I have delted the home in home app and re-imported home bridge... nothing working 

what am I doing wrong

also  my plex devices dont show up either

all working fine in home assistant

**Comment by hdemel** [comment]
I've noticed the exact same issue. All my switches have been found but not all my sensors.

**Comment by bhaap** [comment]
Same here, I've got 2 sensors and then 2 sensors and 2 statistics sensors setup. When i start homebridge it will only find 3/4 sensors (one stat sensor is gone).

**Comment by vswraith** [comment]
For me no temperature sensor shows up

**Comment by vkorn** [comment]
+1. Also don't see any binary_sensor. sensor_class is present

**Comment by bhaap** [comment]
Make shure of this:

Temp sensors should include either "°C" or "°F" as unit of measurement to show up
Humidity sensors need to include "%" as unit of measurement AND have the name "humidity" in the entity_id to show up
Light sensors should include "lux" as unit of measurement to show up

For the original poster, Can you post the name and state of your binary_sensor? (found in the states page in home assistant)

**Comment by duecedriver** [comment]
I did another npm install and also updated homebridge and now i have zwave lights, dimmers, first alert smoke/co binary sensors for alarm state (custom binary sensor) and 

It brings in a couple of yahoo wether values...

Temp max
Temp min 
Temp

All showing as values

And humidity which is showin the same tile as a binary sensor... but displaying humidity ?  Weird

This is the name of humidity sensor in hass config
sensor.yweather_humidity

Does not bring in any other yahoo weather values like visability, wind, etc

Biggest issue now is having to redo the entire setup during reboots, upgrades....
Everything goes away and either shows up in default room and the home app removes all scenes created in home from the inventory.... 

Very frustrating

**Comment by bhaap** [comment]
I've got some resets aswell. I think its a homebridge error thou not a plugin error. 

The humidity tile lookes like the tile at the top middle in this images, if yes then it is the correct image:
https://blog.elgato.com/wp-content/uploads/2016/09/31_EN_abb06.jpg

**Comment by MaKin211** [comment]
Are there any news on that issue? I switched from a Pi2 to a Pi3 and did the same exact setup (using mysensors for Temp and Hum) and unfortunately only the Temp values show up...

**Comment by robbiet480** [comment]
We only support humidity, light and temperature sensors (and soon CO2 sensors). Visibility, wind, etc are not supported in HomeKit.

There's a fix coming out shortly which expands the definition of humidity sensors by allowing you to set the `homebridge_sensor_type` to `humidty` to attempt parsing an entity as a humidity sensor. Previously it was only detected if `humidity` was in the entity ID.
