### ISSUE TITLE
Updgrade questions?

### ISSUE THREAD

**Issue by duecedriver** [home-assistant/homebridge-homeassistant#75]
How do you know there is a new version to install?

Does this plug in auto update on a reboot?

How to you check installed version?

I dont see a current version number for the latest available plug in here on this site...

So in short how do I keep this up to date?

Thanks

**Comment by robbiet480** [comment]
You would need to keep an eye on [Twitter](https://twitter.com/home_assistant) or [NPM](https://npmjs.org/package/homebridge-homeassistant) to know when a new version comes out.

It does not auto update on a reboot

`npm list -g homebridge-homeassistant` will show you the currently installed version.

Versions can be found on the [Releases](https://github.com/home-assistant/homebridge-homeassistant/releases) page on the left side of every release. We tag all releases with the version.
