### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by jharmn** [home-assistant/homebridge-homeassistant#76]
In the spirit of contribution, I created an image for setting up homebridge/homebridge-homeassistant. (props to @valentinalexeev who created this [for RPi](https://hub.docker.com/r/valentinalexeev/rpi-homebridge-homeassistant/) first).

This should clean up a lot better once NPM is updated with the recent commit addressing [external config files](https://github.com/nfarina/homebridge/commit/ecda18029f6d9d106a38f9f3ed673271c4f6e42b). For now the configuration is pretty sketchy. . 

[On Docker Hub](https://hub.docker.com/r/jharmn/docker-homebridge-homeassistant/)

If it's useful to fork/include and/or share in the README, go for it. If not, feel free to close the issue.

**Comment by robbiet480** [comment]
@jharmn Thanks! Looks like NPM was updated with that fix. Can you re-test your Dockerfile and improve where needed to support the external config files/ensure everything still works? Once you let me know you've done so I can merge it into this repo and give you contributor access to keep it updated.

**Comment by tobre6** [comment]
What about automated build, I'm running this quite a while https://hub.docker.com/r/tobre/rpi-homebridge-homeassistant/~/dockerfile/

**Comment by timsamuelsson** [comment]
@tobre6 Your link is a 404, is this the link to mean: https://github.com/tobre6/homebridge-homeassistant/blob/master/Dockerfile

**Comment by tobre6** [comment]
@timsamuelsson I don't use it any more. I'm using this https://hub.docker.com/r/oznu/homebridge/
because it's better maintained.
