### ISSUE TITLE
Renamed devices not reflected in iOS

### ISSUE THREAD

**Issue by maddox** [home-assistant/homebridge-homeassistant#79]
I tried renaming a device with customize in HA, then bounced both HA and Homebridge, but my iPhone still shows the old name. The new name is reflected in the Homebridge log.

Has anyone seen this? If so how can I get the name to change?

**Comment by kolossboss** [comment]
Try to delete the accessoires and/or persist folder in the homebridge config folder. But I think you will lost your room settings, if you do.

You can change the name directly in iOS, too.

**Comment by maddox** [comment]
Yeah, deleting those resets everything. I have over 50 devices. This being
our only option is not an acceptable one.

**Comment by maddox** [comment]
Apparently, this is a limitation of HomeKit. Once it sees a device, the name is permanent in the HomeKit DB. Any name changes have to happen in HomeKit.

per @KhaosT on Twitter:
https://twitter.com/KhaosT/status/848012993287802880
