### ISSUE TITLE
Reverse functionality?

### ISSUE THREAD

**Issue by etsnfrels** [home-assistant/homebridge-homeassistant#81]
I have been using Homebridge as my HA controller for a bit now. I'm currently converting to Home assistant, but it seem that I'm having an issue with my Connected by TCP hub. The homebridge-connectedbytcp plugin is what ive been using, but it doesn't seem that anyone has gotten connectedbytcp working with Homeassistant. Is there a way to use homeassistant to control my homebridge device so that I can control my homebridge-connectedbytcp devices?

**Comment by jamieshaw** [comment]
As far as I know, Homebridge (and HomeKit) are pretty much output only.

The only method I could think off is set up a number of dummy switches in HA, have those exposed in HB and automate those switches to your lights in HK.

**Comment by robbiet480** [comment]
@jamieshaw is correct, Homebridge is output only, there's no way to communicate between plugins.
