### ISSUE TITLE
Automatic/Continuous Device Discovery Needed

### ISSUE THREAD

**Issue by mynameisdaniel32** [home-assistant/homebridge-homeassistant#86]
Firstly, thank you for all the work on this - it works great and I've been using it a lot. I have noticed an issue that has been bugging me - I'm not sure if it's something that needs to be looked at from this plugin's side of things or homebridge.

When I first start up homebridge it detects which ever devices have been loaded into homeassistant at that time and that's it. So if something comes online (say a light, or a chromecast) after this has occurred it won't be discovered and made available in homebridge (it shows up fine in homeassistant).

I haven't been able to get the homebridge service to successfully stop/restart so I end up rebooting my whole RPi while everything in my house is online whenever I need to add something new.

**Comment by jateelover** [comment]
Yup - happens to me with Wemo devices
