### ISSUE TITLE
Lights appears as switches

### ISSUE THREAD

**Issue by radinsky** [home-assistant/homebridge-homeassistant#87]
Hey

I configured my broadlink devices (mainly wall switches) as lights in homeassistant and they appear on web page as light bulbs, but when i open the homekit on iphone it appears as switches.
Somebody familiar?

![image](https://cloud.githubusercontent.com/assets/4540268/21578621/407a1344-cf90-11e6-922c-dc6d8a93e6e4.png)

**Comment by maddox** [comment]
How did you go about making them "lights" in HA? The broadlink compliment
is just a switch.

I'm curious what you did.

**Comment by radinsky** [comment]
Actually started from simple copying the component brodlink from switch to lights

**Comment by maddox** [comment]
Oh you used a custom component.

**Comment by radinsky** [comment]
Any chance you can point where to dig?

**Comment by maddox** [comment]
¯\(°_O)/¯ I have no idea what the code for your component looks like.

**Comment by maddox** [comment]
Wait do you mean you literally just moved the broadlink.py file into the switch directory? If so, that's not enough. The component is a switch. You'd have to make a whole new component that inherits from a light. You can't just move it to another place.

**Comment by radinsky** [comment]
Yes, i know it, started adapting to light component basing on other examples. but if there's a chance you know which file should be affected, created and etc.. would be nice :)

**Comment by bhaap** [comment]
Imo. You can just change the icon to a lightbulb in hass and tell home that it is a light in your phone and be done with it :P Thats what i did :D

**Comment by radinsky** [comment]
Changing icons and type of the switch is good enough workaround for me, thanks..
