### ISSUE TITLE
supported media commands

### ISSUE THREAD

**Issue by kibs** [home-assistant/homebridge-homeassistant#90]
Hi,

I have installed homeassistant and homebridge setup, using homebridge-homeassistant

HomeAssistant provides 10766 as supported media commands for my Sonos equipment, which matches no constant in homebridge-homeassistant, and then an "undefined" service is sent when trying to switch on/off the sonos using homebridge.

**Comment by robbiet480** [comment]
What kind of Sonos do you have and what version of Home Assistant are you using? My Sonos PLAY:3 shows `supported_media_commands: 31263` so I am unable to reproduce your issues currently...

**Comment by kibs** [comment]
My PLAY:3 reports 10766 and my Playbar reports 14879 in Home Assistant 0.35.3, Sonos running latest firmware, but I don't see this as an issue, as the support media commands number is built inside home assistant

**Comment by robbiet480** [comment]
Is this still a problem after using the latest version? A fix was possibly applied in #112. Please let me know if this is still an issue and I will re-open.
