### ISSUE TITLE
Make logging configurable

### ISSUE THREAD

**Issue by nodomain** [home-assistant/homebridge-homeassistant#94]
Since my RPi was flooded with "received event" log entries, I commented out the according line in index.js. Could this also be made configurable? Something like loglevel or similar.

Thanks :)

**Comment by robbiet480** [comment]
Was just thinking about this the other day. Will try to get something done soon.

**Comment by Phileep** [comment]
@nodomain - can you suggest which parts of he index.js you manually changed and to what?

I am not very python and see log mentioned several times.

I am hoping to manually tweak my installation until it is configurable as the log file has eaten my SD card a couple of times already!

**Comment by nodomain** [comment]
I just commented out https://github.com/home-assistant/homebridge-homeassistant/blob/master/index.js#L49

**Comment by robbiet480** [comment]
Closed via 1db67ee0ccb155be0be83cfd58d7f69d210960fc

It's not configurable but it's better than nothing for right now.
