### ISSUE TITLE
If I have a device currently visible to Homekit throught Homebridge, will this plugin allow me to control it through HA?

### ISSUE THREAD

**Issue by poldim** [home-assistant/homebridge-homeassistant#95]
I just got homebridge up and running and used @anthonywebb's awesome plugin (https://github.com/anthonywebb/homebridge-cbus) to get it talking to and controlling my Clipsal home automation system.  I'm trying to understand if if this HB-HA plugin will allow me to control the Clipsal devices in HA.  Is the communication two way with updates in each interafe?

**Comment by robbiet480** [comment]
No.

See also #81.
