### ISSUE TITLE
Readme incorrect

### ISSUE THREAD

**Issue by JoniSykes** [home-assistant/homebridge-homeassistant#97]
Hi :)
Thanks for this awesome plugin. Great work!
Just a heads-up: The readme states that the whitelist 'supported_types' in the config is optional. 
In fact this MUST be present in the config or the platform fails to register and homebridge won't start.
I get that you might have meant it is optional to not include them in this whitelist, but it reads as if that whole line of the config can be excluded, which it cannot.

Thanks.

**Comment by robbiet480** [comment]
Fixed, thanks!
