### ISSUE TITLE
MQTT JSON Light is not dimmable

### ISSUE THREAD

**Issue by sebastianapw** [home-assistant/homebridge-homeassistant#98]
Hi, 
I had HomeBridge running with HomeAssistant for a while now, after updating to the newest version of HomeBridge and the HomeAssistant plugin my MQTT JSON Lights aren't dimmable any longer. 
Before updating the LED Strips were dimmable over the control center in IOS and they are still dimmable on the HomeAssistant WebApp.
Is this problem already known?

Best regards

**Comment by niggydotcom** [comment]
For Hue lights get this:

/usr/local/lib/node_modules/homebridge-homeassistant/accessories/light.js:139
            this.log('Setting brightness on the \''+this.name+'\' to ' + level);
TypeError: this.log is not a function
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-homeassistant/accessories/light.js:139:18)

or

/usr/local/lib/node_modules/homebridge-homeassistant/accessories/light.js:140
            this.client.callService(this.domain, 'turn_on', service_data, function(data){
                       ^
TypeError: Cannot read property 'callService' of undefined
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-homeassistant/accessories/light.js:140:24)

**Comment by KmanOz** [comment]
+1 on this. In fact if I ask Siri to adjust any setting on an MQTT light other than on or off, Homebridge crashes completely.
![img_0633](https://cloud.githubusercontent.com/assets/1904926/22722228/ae8ad340-ee09-11e6-8c99-2527ae893cd3.JPG)

**Comment by robbiet480** [comment]
@KmanOz A hotfix was released last night as 2.0.3, are you on that version?

**Comment by KmanOz** [comment]
I am now LOL. Thanks Robbie. All good
