### ISSUE TITLE
Log file spam

### ISSUE THREAD

**Issue by jamieshaw** [home-assistant/homebridge-homeassistant#99]
Just had an incident where my Homebridge log rapidly burnt through *all* available storage on my SSD on my Mac mini.  As far as I'm aware, after setup, Homebridge pushed minimal information to the log such as triggers, fails, etc.

Home Assistant, however, is pushing JSON dumps of practically every event. Is this necessary? Can it be turned off?

**Comment by robbiet480** [comment]
Closed via 1db67ee0ccb155be0be83cfd58d7f69d210960fc
